Repository dimagi/commcare-android, pull requests merged in 2018-02, with the labels that each got.

#1943 Fixes NPE on rotation for Update Prompts
  app/src/org/commcare/activities/PromptUpdateActivity.java
Labels: bug, minor (quick review), product/all-users, ready for review

#1944 Explicitly Deleting deleted files from gallery
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
Labels: bug, minor (quick review), product/all-users, ready for review

#1948 More Crashes
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/provider/InstanceProvider.java
Labels: minor (quick review), product/invisible

#1947 Return RESULT_OK for external callouts
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: bug, product/invisible

#1946 Improve UX when Installs/Updates Fail with a Notification
  app/assets/locales/android_translatable_strings.txt
  app/original_vector_graphics/list.svg
  app/original_vector_graphics/list_error.svg
  app/res/drawable/ic_list_error.xml
  app/res/layout/rectangle_button_text.xml
  app/res/layout/screen_login.xml
  app/res/layout/select_install_mode_fragment.xml
  app/res/layout/update_activity.xml
  app/res/values-large/dimens.xml
  app/res/values-small/dimens.xml
  app/res/values-xlarge/dimens.xml
  app/res/values/dimens.xml
  app/res/values/strings.xml
  app/src/org/commcare/CommCareNoficationManager.java
  app/src/org/commcare/activities/BlankLoginActivityUIController.java
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/LoginActivityUIController.java
  app/src/org/commcare/activities/UpdateActivity.java
  app/src/org/commcare/activities/UpdateUIController.java
  app/src/org/commcare/fragments/SelectInstallModeFragment.java
Labels: enhancement, minor (quick review), product/all-users, ready for review

#1951 Updates landscape layout for update activity with recent changes
  app/res/layout-land/update_activity.xml
  app/res/layout/update_activity.xml
Labels: bug, minor (quick review), product/invisible

#1945 Vary update prompt frequency
  app/src/org/commcare/activities/PromptUpdateActivity.java
  app/src/org/commcare/heartbeat/UpdatePromptHelper.java
  app/src/org/commcare/heartbeat/UpdatePromptShowHistory.java
  app/src/org/commcare/heartbeat/UpdateToPrompt.java
  app/src/org/commcare/preferences/MainConfigurablePreferences.java
  app/unit-tests/src/org/commcare/android/tests/HeartbeatAndPromptedUpdateTests.java
Labels: cross requested, product/custom, ready for review

#1954 Adds style guidelines to Readme
  README.md
Labels: product/invisible, ready for review

#1950 Split non-DB centric sorting into commcare-core utility
  app/src/org/commcare/adapters/EntityStringFilterer.java
Labels: product/invisible

#1955 Make properties of type String so values from HQ are compatible
  app/src/org/commcare/heartbeat/UpdateToPrompt.java
Labels: bug, minor (quick review), product/invisible, ready for review
