Repository dimagi/commcare-android, pull requests merged in 2018-03, with the labels that each got.

#1953 Error button visibility fix
  app/src/org/commcare/fragments/SelectInstallModeFragment.java
Labels: bug, product/invisible, ready for review

#1959 2.42.1 hotfix -- Revert sorting the saved forms list by submission ordering number
  app/src/org/commcare/adapters/IncompleteFormListAdapter.java
Labels: bug, minor (quick review), product/all-users, ready for review

#1960 Removes stranded setTransactionSuccesful
  app/src/org/commcare/adapters/EntityStringFilterer.java
Labels: bug, minor (quick review), product/invisible, ready for review

#1957 Adds mechanism to set image path for Image widget through a broadcast
  app/AndroidManifest.xml
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/provider/DebugControlsReceiver.java
  app/src/org/commcare/views/widgets/ImageWidget.java
Labels: product/invisible, ready for review

#1961 Method name changed
  app/src/org/commcare/models/AndroidSessionWrapper.java
Labels: cross requested, minor (quick review), product/invisible, ready for review

#1952 Target Specific CommCare Flavor
  app/assets/locales/android_translatable_strings.txt
  app/res/layout/layout_note_msg.xml
  app/res/layout/screen_messages.xml
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/engine/resource/installers/LocalStorageUnavailableException.java
  app/src/org/commcare/engine/resource/installers/SingleAppInstallation.java
  app/src/org/commcare/tasks/ResourceEngineListener.java
  app/src/org/commcare/tasks/ResourceEngineTask.java
  app/src/org/commcare/utils/FormUploadUtil.java
Labels: cross requested, enhancement, product/all-users, ready for review

#1963 Fixes no error message issue in sms install
  app/src/org/commcare/activities/CommCareSetupActivity.java
Labels: minor (quick review), product/invisible, ready for review

#1958 Revert "Sort completed forms in form record list by submission ordering number"
  app/src/org/commcare/adapters/IncompleteFormListAdapter.java
Labels: bug, minor (quick review), product/all-users, ready for review

#1962 Requests for camera permission in ImageWidget in case it's not already granted
  app/assets/locales/android_startup_strings.txt
  app/assets/locales/android_translatable_strings.txt
  app/res/values/strings.xml
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/utils/Permissions.java
  app/src/org/commcare/views/widgets/ImageWidget.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: bug, product/all-users, ready for review

#1956 Add 'Training' button to home screen
  app/assets/locales/android_translatable_strings.txt
  app/original_vector_graphics/home_start.svg
  app/original_vector_graphics/home_training.svg
  app/res/drawable-hdpi/ic_training_nav_drawer.png
  app/res/drawable-mdpi/ic_training_nav_drawer.png
  app/res/drawable-xhdpi/ic_training_nav_drawer.png
  app/res/drawable-xxhdpi/ic_training_nav_drawer.png
  app/res/drawable/home_start.xml
  app/res/drawable/home_training.xml
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/activities/HomeButtons.java
  app/src/org/commcare/activities/HomeNavDrawerController.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/RootMenuHomeActivity.java
  app/src/org/commcare/activities/StandardHomeActivityUIController.java
  app/src/org/commcare/adapters/MenuAdapter.java
Labels: cross requested, product/custom, ready for review

#1965 Fix overriding of last username
  app/src/org/commcare/activities/LoginActivity.java
Labels: bug, minor (quick review), product/all-users, ready for review
