Repository dimagi/commcare-android, pull requests merged in 2018-04, with the labels that each got.

#1966 Fixes Save in FormEntry after Resuming Session
  app/src/org/commcare/activities/FormEntryActivity.java
Labels: minor (quick review), product/all-users, ready for review

#1968 Enables Change Language Option in Practice Mode
  app/src/org/commcare/activities/StandardHomeActivity.java
  app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java
Labels: minor (quick review), product/all-users, ready for review

#1969 Make noun project credit translatable (for CAS)
  app/res/values/strings.xml
Labels: minor (quick review), product/custom, ready for review

#1970 Fix 2 NPEs from crashlytics
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: bug, minor (quick review), product/invisible, ready for review

#1972 Fix for Pre v17 Upgrade Path on Case Model
  app/src/org/commcare/android/database/user/models/ACasePreV6Model.java
Labels: bug, product/invisible, ready for review

#1973 Bugfix: Update from pre relationship index table when origin db is v5 or below
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
Labels: bug, product/invisible, ready for review

#1974 Target specific flavour: Show Link to Open/Install App on Error Screen
  app/AndroidManifest.xml
  app/assets/locales/android_translatable_strings.txt
  app/res/layout/activity_target_mismatch_error.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/TargetMismatchErrorActivity.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/tasks/ResourceEngineListener.java
  app/src/org/commcare/tasks/ResourceEngineTask.java
Labels: product/all-users, ready for review

#1975 Null checks
  app/src/org/commcare/activities/EntitySelectActivity.java
Labels: bug, minor (quick review), product/invisible, ready for review

#1977 Logs resource init failures to Device Logs
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
Labels: minor (quick review), product/invisible, ready for review

#1976 Add implementation of fail fast method
  app/src/org/commcare/models/database/AndroidSandbox.java
Labels: bug, cross requested, minor (quick review), product/invisible, ready for review

#1978 Change definition of successful Simprints callout processing
  app/src/org/commcare/provider/SimprintsCalloutProcessing.java
Labels: minor (quick review), product/invisible, ready for review

#1980 Update Markdown llibrary
  app/AndroidManifest.xml
  app/build.gradle
  app/proguard.cfg
  app/src/org/commcare/utils/MarkupUtil.java
Labels: product/invisible

#1967 Adds Data change logs along with Kotlin Support
  app/AndroidManifest.xml
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/res/drawable/ic_share_24dp.xml
  app/res/layout/activity_data_change_logs.xml
  app/res/menu/menu_share.xml
  app/res/values/strings.xml
  app/res/xml/app_manager_preferences.xml
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/AppManagerAdvancedPreferences.java
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/DataChangeLogsActivity.java
  app/src/org/commcare/activities/SingleAppManagerActivity.java
  app/src/org/commcare/activities/UpdateActivity.java
  app/src/org/commcare/android/logging/ReportingUtils.java
  app/src/org/commcare/logging/DataChangeLog.kt
  app/src/org/commcare/logging/DataChangeLogger.kt
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
  app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/tasks/UpdateTask.java
  app/src/org/commcare/utils/CrashUtil.java
  app/src/org/commcare/views/CommCareShareActionProvider.java
  build.gradle
  scripts/ccc
Labels: product/all-users, ready for review

#1984 Don't exit before adding url param
  app/src/org/commcare/engine/resource/ResourceInstallUtils.java
Labels: product/invisible

#1983 Replaces remaining old http code with Retrofit based code
  app/build.gradle
  app/src/org/commcare/network/DataSubmissionEntity.java
  app/src/org/commcare/network/HttpCalloutTask.java
  app/src/org/commcare/network/LocalReferencePullResponse.java
  app/src/org/commcare/network/mocks/LocalFilePullResponse.java
  app/src/org/commcare/tasks/ConnectionDiagnosticTask.java
Labels: cross requested, product/invisible, ready for review

#1982 Updates to Android Gradle Plugin 3.0.1 and Gradle 4.7
  app/AndroidManifest.xml
  app/build.gradle
  app/proguard.cfg
  app/res/values-v11/themes.xml
  app/res/values-v14/themes.xml
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: cross requested, product/invisible, ready for review

#1987 Hide home screen training button if its menus are hidden
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/activities/HomeNavDrawerController.java
  app/src/org/commcare/activities/StandardHomeActivityUIController.java
Labels: don't pull, product/custom, question, ready for review

#1988 Reverts to not showing warning when saving Incomplete forms
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: minor (quick review), product/invisible

#1990 2.43 - remove 'NEW' text
  app/assets/locales/android_startup_strings.txt
Labels: minor (quick review), product/invisible, ready for review
