Repository dimagi/commcare-android, pull requests merged in 2018-06, with the labels that each got.

#2008 Initializing a CommCareApp should fail if a resource fails to initialize
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/android/resource/installers/LocaleAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/MediaFileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/OfflineUserRestoreAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstallerV1.java
  app/src/org/commcare/android/resource/installers/XFormUpdateInfoInstaller.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/heartbeat/HeartbeatLifecycleManager.java
  app/src/org/commcare/tasks/InstallStagedUpdateTask.java
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
  app/src/org/commcare/utils/DummyResourceTable.java
Labels: bug, cross requested, product/invisible, ready for review

#2009 Add more logs to debug missing app files issue
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/android/resource/installers/FileSystemUtils.java
  app/src/org/commcare/logging/DataChangeLogger.kt
Labels: cross requested, minor (quick review), product/invisible

#2006 Incorrect Time Notification
  app/res/values/strings.xml
  app/src/org/commcare/AndroidPreferenceManager.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/DriftHelper.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/heartbeat/HeartbeatRequester.java
  app/src/org/commcare/preferences/DeveloperPreferences.java
  app/src/org/commcare/utils/AndroidInstanceInitializer.java
Labels: product/internal-or-flagged, ready for review

#2010 Add external_id as indexable case property
  app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
  app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
Labels: product/invisible

#1931 In-form caching
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/preferences/DeveloperPreferences.java
  app/src/org/commcare/tasks/FormLoaderTask.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
  app/unit-tests/src/org/commcare/android/tests/queries/ExpressionCacheTest.java
  app/unit-tests/src/org/commcare/android/util/TestUtils.java
  app/unit-tests/src/org/commcare/utils/FormCacheEligibilityTester.java
Labels: cross requested, product/invisible, ready for review

#2013 Fixes User DB v5->6 migration caused by Case Relationship
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
  app/src/org/commcare/models/database/user/models/AndroidCaseIndexTableV1.java
Labels: bug, product/invisible, ready for review
