Repository dimagi/commcare-android, pull requests merged in 2018-05, with the labels that each got.

#1979 Device log cleaning
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/CommCareWiFiDirectActivity.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/activities/RecoveryActivity.java
  app/src/org/commcare/adapters/MenuAdapter.java
  app/src/org/commcare/android/database/global/models/AndroidSharedKeyRecord.java
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/android/javarosa/IntentCallout.java
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/fragments/BreadcrumbBarFragment.java
  app/src/org/commcare/fragments/FileServerFragment.java
  app/src/org/commcare/fragments/WiFiDirectManagementFragment.java
  app/src/org/commcare/heartbeat/HeartbeatRequester.java
  app/src/org/commcare/models/database/SqlStorage.java
  app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
  app/src/org/commcare/models/database/migration/FixtureSerializationMigration.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/services/WiFiDirectBroadcastReceiver.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/EntityLoaderTask.java
  app/src/org/commcare/tasks/FormLoaderTask.java
  app/src/org/commcare/tasks/FormRecordCleanupTask.java
  app/src/org/commcare/tasks/ManageKeyRecordTask.java
  app/src/org/commcare/tasks/ProcessAndSendTask.java
  app/src/org/commcare/tasks/PurgeStaleArchivedFormsTask.java
  app/src/org/commcare/tasks/templates/CommCareTask.java
  app/src/org/commcare/utils/FormUploadUtil.java
  app/src/org/commcare/views/EntityView.java
  app/src/org/commcare/views/EntityViewTile.java
  app/src/org/commcare/views/QuestionsView.java
Labels: cross requested, product/invisible, ready for review

#1985 Adds test for DataChangeLogger
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
  app/unit-tests/src/org/commcare/android/CommCareTestRunner.java
  app/unit-tests/src/org/commcare/android/tests/activities/FormRecordListActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/formentry/FormIntentTests.java
  app/unit-tests/src/org/commcare/android/tests/formentry/IntentCalloutTests.java
  app/unit-tests/src/org/commcare/android/tests/formnav/CalendarLocaleTest.java
  app/unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java
  app/unit-tests/src/org/commcare/android/tests/formsave/FormRecordProcessingTest.java
  app/unit-tests/src/org/commcare/logging/DataChangeLoggerTest.java
Labels: product/invisible, ready for review

#1993 Backmerge 2.43
  app/assets/locales/android_startup_strings.txt
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/activities/HomeNavDrawerController.java
  app/src/org/commcare/activities/StandardHomeActivityUIController.java
Labels: product/invisible

#1995 Commcare 2.43 Backmerge
  app/build.gradle
Labels: product/invisible

#1999 Don't have a translatable string span multiple lines
  app/res/values/strings.xml
Labels: bug, minor (quick review), product/invisible, ready for review

#1998 Close resources
  app/build.gradle
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/models/database/AndroidPrototypeFactorySetup.java
  app/src/org/commcare/tasks/LogSubmissionTask.java
  build.gradle
  gradle.properties
Labels: bug, product/invisible

#2004 Remove concept of being able to edit a form after it's completed
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/components/FormEntryInstanceState.java
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
  app/src/org/commcare/provider/InstanceProviderAPI.java
  app/src/org/commcare/tasks/FormRecordCleanupTask.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
  app/src/org/commcare/xml/FormInstanceXmlParser.java
Labels: cross requested, product/invisible, ready for review

#2003 Cursor npe
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
Labels: bug, don't pull, minor (quick review), product/invisible

#2005 Set submission ordering # at same time we mark a form as completed
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/android/database/app/models/FormDefRecord.java
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: bug, minor (quick review), product/invisible

#2007 Update android.support libs to 27.1.1
  app/build.gradle
Labels: product/invisible
