Repository dimagi/commcare-android, pull requests merged in 2018-07, with the labels that each got.

#2014 Corrects External Id Migration for v17-18, Fixes case Relationship migration for v18-19
  app/src/org/commcare/android/database/user/models/ACasePreV24Model.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
  app/src/org/commcare/models/database/user/models/AndroidCaseIndexTable.java
  app/src/org/commcare/models/database/user/models/AndroidCaseIndexTablePreV21.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: bug, product/invisible, ready for review

#2016 Backmerge Commcare 2.44
  app/src/org/commcare/android/database/user/models/ACasePreV24Model.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
  app/src/org/commcare/models/database/user/models/AndroidCaseIndexTable.java
  app/src/org/commcare/models/database/user/models/AndroidCaseIndexTablePreV21.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: product/invisible

#2018 Adds crash log for Unique form id constraint failure
  app/src/org/commcare/models/AndroidSessionWrapper.java
Labels: minor (quick review), product/invisible

#2017 Migration fix for Upgrade and Recovery Table
  app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
Labels: bug, critical-bug-fix, product/invisible, ready for review

#2020 Backmerge Commcare 2.44.1
  app/src/org/commcare/models/AndroidSessionWrapper.java
  app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
Labels: don't pull, product/invisible

#2015 Re-download missing Resources from Recovery Screen
  app/res/layout/screen_recovery.xml
  app/res/values/strings.xml
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/activities/RecoveryActivity.java
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/android/resource/installers/LocaleAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/engine/references/JavaFileReference.java
  app/src/org/commcare/tasks/ProcessAndSendTask.java
  app/src/org/commcare/tasks/ResourceRecoveryTask.java
  app/src/org/commcare/utils/DummyResourceTable.java
Labels: cross requested, product/all-users, ready for review

#2001 Add Strict Mode to debug builds
  app/src/org/commcare/CommCareApplication.java
Labels: product/invisible

#2021 Fixes Crash due to SSD records getting detached in FormProvider Migration
  app/src/org/commcare/android/database/user/models/SessionStateDescriptor.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
Labels: critical-bug-fix, product/invisible, ready for review

#2022 Backmerge Commcare 2.44.2
  app/src/org/commcare/android/database/user/models/SessionStateDescriptor.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
Labels: product/invisible

#2023 Fixes bug in updating File path for an existing Form with new file path
  app/src/org/commcare/android/database/app/models/FormDefRecord.java
  app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
Labels: bug, critical-bug-fix, product/invisible, ready for review

#2025 Backmerge Commcare 2.44
  app/src/org/commcare/android/database/app/models/FormDefRecord.java
  app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
Labels: product/invisible
