Repository dimagi/commcare-android, pull requests merged in 2019-03, with the labels that each got.

#2088 Corrects eval context for menu relevance condition
  app/src/org/commcare/CommCareApp.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2086 Fixes CCZ Install during Recovery
  app/res/values/strings.xml
  app/src/org/commcare/engine/resource/ResourceInstallUtils.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresActivity.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresPresenter.java
Labels: bug, product/invisible, ready for review

#2089 Protects wipeTable call with a tableExists check
  app/src/org/commcare/models/database/SqlStorage.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2090 Don't update if we are already up to date
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresPresenter.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2091 Backmerge Commcare 2.45
  app/res/layout/edit_text_question_widget.xml
  app/res/layout/edit_text_question_widget_compact.xml
  app/res/layout/menu_list_header.xml
  app/res/values/strings.xml
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/activities/EntitySelectSearchUI.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/UpdateActivity.java
  app/src/org/commcare/activities/components/MenuList.java
  app/src/org/commcare/engine/resource/ResourceInstallUtils.java
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresActivity.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresPresenter.java
  app/src/org/commcare/views/widgets/DecimalWidget.java
Labels: product/invisible

#2092 Catch XPathExceptions from training menu related evaluations
  app/src/org/commcare/CommCareApp.java
Labels: minor (quick review), product/invisible, ready for review

#2094 Feature/commcare support text
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
Labels: minor (quick review), product/all-users, ready for review

#2097 Bug fix: Saving a form as Incomplete more than once doesn't work
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/logic/AndroidFormController.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: critical-bug-fix, minor (quick review), product/all-users, ready for review

#2098 Backmerge Commcare 2.45.1
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/logic/AndroidFormController.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: product/invisible
