Repository dimagi/commcare-android, pull requests merged in 2019-04, with the labels that each got.

#2101 Adds LTS debug in google services template
  app/templates/google-services.json
Labels: minor (quick review), product/invisible, ready for review

#2103 Corrections in String File
  app/assets/locales/android_translatable_strings.txt
  app/res/values/strings.xml
Labels: minor (quick review), product/invisible, ready for review

#2093 changed provider exported to false
  app/AndroidManifest.xml
Labels: minor (quick review), product/invisible, ready for review

#2095 added rxBindings; added rx item click listener;
  app/build.gradle
  app/src/org/commcare/activities/EntitySelectActivity.java
Labels: minor (quick review), product/all-users, ready for review

#2096 added glide for GIF image loading
  app/build.gradle
  app/src/org/commcare/views/media/MediaLayout.java
Labels: Release Note, minor (quick review), product/all-users, ready for review

#2099 added sorting for unsaved forms
  app/src/org/commcare/adapters/IncompleteFormListAdapter.java
  app/src/org/commcare/utils/StorageUtils.java
Labels: minor (quick review), product/all-users, ready for review

#2104 Fixes form submission in practice mode
  app/src/org/commcare/network/CommcareRequestGenerator.java
Labels: bug, minor (quick review), product/all-users, ready for review

#2107 [HOTFIX] Revert "Turns Image scaling code path off"
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
Labels: bug, critical-bug-fix, product/all-users

#2108 Backmerge Commcare 2.45.2
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
Labels: product/invisible

#2106 Improve Sync Request hashing performance
  app/src/org/commcare/engine/cases/CaseUtils.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
  app/unit-tests/src/org/commcare/android/tests/processing/ProcessingTest.java
Labels: cross requested, enhancement, product/invisible

#2110 Stops Images from getting shown in Gallery
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/views/widgets/ImageWidget.java
Labels: bug, minor (quick review), product/all-users, ready for review

#2109 Added check: if there is no question on the screen, save form and exit
  app/src/org/commcare/activities/FormEntryActivityUIController.java
Labels: bug, minor (quick review), product/all-users, ready for review

#2085 Adds support for last_sync attribute for Indexed Fixtures
  app/src/org/commcare/engine/cases/AndroidIndexedFixtureInstanceTreeElement.java
  app/src/org/commcare/models/database/AndroidSandbox.java
  app/src/org/commcare/models/database/IndexedFixturePathUtils.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/utils/AndroidInstanceInitializer.java
  app/unit-tests/resources/indexed_fixture_restore.xml
  app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java
  app/unit-tests/src/org/commcare/android/util/TestUtils.java
Labels: cross requested, enhancement, product/internal-or-flagged, ready for review

#2100 Added discard button to image widget
  app/res/values-es/strings.xml
  app/res/values-fr/strings.xml
  app/res/values-lt/strings.xml
  app/res/values-no/strings.xml
  app/res/values-pt/strings.xml
  app/res/values-sw/strings.xml
  app/res/values/strings.xml
  app/src/org/commcare/views/widgets/ImageWidget.java
Labels: Release Note, don't pull, minor (quick review), product/all-users, ready for review

#2102 Updated app name in action bar.
  app/build.gradle
  app/res/values/strings.xml
  app/src/org/commcare/android/database/global/models/ApplicationRecord.java
  app/src/org/commcare/fragments/BreadcrumbBarFragment.java
Labels: minor (quick review), product/custom, ready for review
