Repository dimagi/commcare-android, pull requests merged in 2019-12, with the labels that each got.

#2153 Handle null values in callout response keys
  app/src/org/commcare/android/javarosa/IntentCallout.java
Labels: bug, product/invisible, ready for review

#2152 Fixes NPE in Form List Screen
  app/src/org/commcare/activities/FormRecordListActivity.java
Labels: bug, minor (quick review), product/invisible

#2155 Better Form Save Log
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: product/invisible, ready for review

#2154 Save as Incomplete Navigation fix for external launch
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2157 Fix sync condition being default
  app/src/org/commcare/activities/UpdateActivity.java
Labels: product/invisible
