Repository dimagi/commcare-android, pull requests merged in 2019-02, with the labels that each got.

#2063 Error Improvements Plus Logging
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/views/notifications/NotificationMessageFactory.java
Labels: minor (quick review), product/invisible

#2066 Refreshes menu on app change
  app/src/org/commcare/activities/LoginActivity.java
Labels: minor (quick review), product/all-users, ready for review

#2065 Fixing Entity Detail View to not cut content
  app/res/layout/component_entity_detail_item.xml
  app/res/layout/entity_detail_list.xml
Labels: bug, minor (quick review), product/invisible, ready for review

#2064 Disable log submission requests in case logging is disabled
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/tasks/LogSubmissionTask.java
Labels: cross requested, minor (quick review), product/invisible, ready for review

#2070 Fixed Crash when selecting a file from Downloads folder
  app/src/org/commcare/utils/UriToFilePath.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2069 NPE in Update Activity
  app/src/org/commcare/activities/UpdateUIController.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2060 Throws better error on resource file not found during install
  app/res/values/strings.xml
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/engine/references/ArchiveFileReference.java
Labels: cross requested, product/invisible, ready for review

#2067 Shows 406 error messages from HQ while App update
  app/src/org/commcare/engine/references/JavaHttpReference.java
  app/src/org/commcare/network/HttpUtils.java
  app/src/org/commcare/network/RemoteDataPullResponse.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/utils/FormUploadUtil.java
Labels: minor (quick review), product/invisible, ready for review

#2071 Fix for RtL layouts with audio buttons
  app/res/layout/small_audio_playback.xml
  app/res/values/dimens.xml
  app/src/org/commcare/views/media/AudioPlaybackButtonBase.java
  app/src/org/commcare/views/media/MediaLayout.java
Labels: minor (quick review), product/all-users, ready for review

#2073 Removes Up button from Login Screen
  app/src/org/commcare/activities/LoginActivity.java
Labels: minor (quick review), product/all-users, ready for review

#2072 Fix for CommCare not getting filePath for Files selected from File Explorer 'Recent' option
  app/src/org/commcare/utils/UriToFilePath.java
Labels: bug, minor (quick review), product/all-users, ready for review

#2076 Fixes alignment for Menu List Header
  app/res/layout/menu_list_header.xml
  app/src/org/commcare/activities/components/MenuList.java
Labels: minor (quick review), product/invisible, ready for review

#2074 Form Entry Menu Alignment Fix for RTL
  app/src/org/commcare/activities/FormEntryActivity.java
Labels: minor (quick review), product/invisible, ready for review

#2078 Corrects APP DB version
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2080 Start Align Text in String widget to support for RTL
  app/res/layout/edit_text_question_widget.xml
  app/res/layout/edit_text_question_widget_compact.xml
Labels: bug, minor (quick review), product/invisible, ready for review

#2082 Restore search on getting back to the Case list
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/activities/EntitySelectSearchUI.java
Labels: bug, minor (quick review), product/all-users, ready for review

#2079 Always format Decimal Widget as English
  app/src/org/commcare/views/widgets/DecimalWidget.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2087 Install update as part of recovery measures
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/UpdateActivity.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresActivity.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresPresenter.java
Labels: enhancement, product/invisible, ready for review
