Repository dimagi/commcare-android, pull requests merged in 2019-07, with the labels that each got.

#2124 Don't retry form submissions when rate limited
  app/src/org/commcare/tasks/ProcessAndSendTask.java
  app/src/org/commcare/utils/FormUploadResult.java
  app/src/org/commcare/utils/FormUploadUtil.java
Labels: enhancement, minor (quick review), product/invisible

#2123 Correct error handling for Indexed Fixture atrribute lookup
  app/src/org/commcare/engine/cases/AndroidIndexedFixtureInstanceTreeElement.java
Labels: minor (quick review), product/invisible, ready for review

#2122 Moves Indexed Fixture attribute lookup methods to core
  app/src/org/commcare/engine/cases/AndroidIndexedFixtureInstanceTreeElement.java
  app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java
Labels: cross requested, product/invisible, ready for review

#2127 Catches Xpath error in onEntitySelected
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/activities/FormEntryActivity.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2128 [HOTFIX] [commcare_2.47.2] Fixes saved forms reading issue when there are duplicate namespaces in Forms table
  app/src/org/commcare/activities/components/FormEntryInstanceState.java
  app/src/org/commcare/android/database/app/models/FormDefRecord.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Labels: bug, critical-bug-fix, product/invisible, ready for review

#2126 Fixes for ProtoType Audio Widget
  app/src/org/commcare/views/widgets/CommCareAudioWidget.java
  app/src/org/commcare/views/widgets/RecordingFragment.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2129 Backmerge Commcare 2.47.2
  app/AndroidManifest.xml
  app/src/org/commcare/activities/components/FormEntryInstanceState.java
  app/src/org/commcare/android/database/app/models/FormDefRecord.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Labels: product/invisible
