Repository dimagi/commcare-android, pull requests merged in 2020-03, with the labels that each got.

#2188 Backmerge Commcare 2.47.6
  app/AndroidManifest.xml
  app/src/org/commcare/activities/components/FormEntryInstanceState.java
  app/src/org/commcare/android/database/app/models/FormDefRecord.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
Labels: product/invisible

#2189 Backmerging 2.47.6 hotfix in Commcare 2.48
  app/AndroidManifest.xml
  app/src/org/commcare/activities/components/FormEntryInstanceState.java
  app/src/org/commcare/android/database/app/models/FormDefRecord.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
Labels: product/invisible

#2190 Disable retries on getting rate limited on individual resource requests
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/engine/references/JavaHttpReference.java
  app/src/org/commcare/network/RateLimitedException.java
Labels: enhancement, minor (quick review), product/invisible

#2191 add github sponsorship
  .github/FUNDING.yml
Labels: product/invisible

#2194 Changes Sync Pending calculation to give AUTO_SYNC_FREQUENCY priority over cc-auto-update
  app/src/org/commcare/utils/PendingCalcs.java
Labels: minor (quick review), product/all-users, ready for review

#2192 Fix mismatched attachments while editing a saved form
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/activities/components/FormRelevancyUpdating.java
  app/src/org/commcare/views/widgets/ImageWidget.java
Labels: critical-bug-fix, product/all-users, ready for review

#2196 Commcare 2.48
  app/AndroidManifest.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/components/FormRelevancyUpdating.java
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/engine/references/JavaHttpReference.java
  app/src/org/commcare/network/RateLimitedException.java
  app/src/org/commcare/views/widgets/ImageWidget.java
Labels: product/invisible

#2193 [no op] Removes syncPending
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: minor (quick review), product/invisible, ready for review

#2199 Add forms with status complete to the unsent filter
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/views/IncompleteFormRecordView.java
Labels: critical-bug-fix, product/all-users

#2198 Shows custom App Version Tag in About CommCare
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/preferences/HiddenPreferences.java
Labels: minor (quick review), product/all-users, ready for review

#2197 Fix for navigation of saved form
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/activities/components/FormEntryConstants.java
  app/src/org/commcare/activities/components/FormEntryDialogs.java
Labels: product/all-users, ready for review

#2201 Sets Pre update Sync needed from the staged update
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/preferences/HiddenPreferences.java
Labels: bug, minor (quick review), product/invisible, ready for review
