Repository dimagi/commcare-android, pull requests merged in 2020-11, with the labels that each got.

#2390 Add session expiration test
  app/instrumentation-tests/resources/session_expiration.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/SessionExpirationTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/TilesTest.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
Labels: minor (quick review), product/invisible

#2399 Fix clear button styling and add click handler
  app/instrumentation-tests/resources/clear_button_test.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/ClearButtonTest.kt
  app/src/org/commcare/views/widgets/SelectOneAutoAdvanceWidget.java
  app/src/org/commcare/views/widgets/SelectOneWidget.java
  app/src/org/commcare/views/widgets/WidgetUtils.java
Labels: product/invisible

#2396 Add manual quarantine tests
  README.md
  app/instrumentation-tests/resources/ccqa.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/AsyncRestoreTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/CaseClaimTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/CaseListSearchTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/CaseListSortTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/CaseSharingTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/ClearButtonTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DemoUserOfflineTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DemoUserOnlineTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DialogTests.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FixturesTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FormAttachmentUploadTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/FormEntryTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FormFilteringTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FormSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/InstallFromListTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LanguagesTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LogSubmissionTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LookupTableTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/ManualQuarantineTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/MenuTests.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SavedFormTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/SessionExpirationTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SubmissionErrorResponseTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SyncRecoveryTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/TilesTest.kt
  app/instrumentation-tests/src/org/commcare/annotations/BrowserstackTests.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
  scripts/browserstack.py
Labels: product/invisible, ready for review

#2402 Stop submitting logs if rate limit is reached
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/tasks/LogSubmissionTask.java
Labels: product/invisible

#2389 [2.50.3] Deletes Raw Folder on Form Completion + Free Disk space Analytics
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/DiskUtils.kt
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
  app/src/org/commcare/utils/StorageUtils.java
  app/src/org/commcare/views/widgets/CleanRawMedia.kt
  app/src/org/commcare/views/widgets/ImageWidget.java
Labels: product/all-users

#2401 Fix form jump issues with edittext
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/views/widgets/StringWidget.java
Labels: bug, product/all-users

#2404 Adds "XPathEncryptStringFunc" to fix testAllExternalizablesInPrototypeFactory
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: product/invisible, ready for review

#2406 Remove duplicate commcareVersion from strings.xml
  app/res/values/strings.xml
  app/src/org/commcare/CommCareApplication.java
Labels: minor (quick review), product/invisible

#2409 [2.50.3] Lets Encrypt Root CA Change
  app/build.gradle
  app/instrumentation-tests/src/org/commcare/androidTests/LetsEncryptTest.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/network/ISRGCertConfig.java
  app/src/org/commcare/network/Tls12SocketFactory.java
Labels: product/invisible, ready for review

#2408 Optimize android instrumentation test time
  app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/CaseSharingTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/MenuTests.kt
  app/instrumentation-tests/src/org/commcare/utils/CustomMatchers.kt
  scripts/browserstack.py
Labels: minor (quick review), product/invisible, ready for review

#2405 Allow use of custom barcode scanner apps
  app/res/xml/main_preferences.xml
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/activities/GlobalPrivilegeClaimingActivity.java
  app/src/org/commcare/activities/QueryRequestActivity.java
  app/src/org/commcare/activities/components/EntitySelectCalloutSetup.java
  app/src/org/commcare/fragments/SelectInstallModeFragment.java
  app/src/org/commcare/preferences/MainConfigurablePreferences.java
  app/src/org/commcare/views/widgets/BarcodeWidget.java
  app/src/org/commcare/views/widgets/WidgetUtils.java
Labels: product/all-users

#2410 Initialize TLS1.2 before adding the isrg cert
  app/src/org/commcare/CommCareApplication.java
Labels: product/invisible, ready for review
