Repository dimagi/commcare-android, pull requests merged in 2020-12, with the labels that each got.

#2415 Avoid using 5 shards when number of tests are low
  scripts/browserstack.py
Labels: bug, product/invisible

#2413 Backmerge Commcare 2.50.3
  app/build.gradle
  app/instrumentation-tests/src/org/commcare/androidTests/LetsEncryptTest.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/DiskUtils.kt
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/network/ISRGCertConfig.java
  app/src/org/commcare/network/Tls12SocketFactory.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
  app/src/org/commcare/utils/StorageUtils.java
  app/src/org/commcare/views/widgets/CleanRawMedia.kt
  app/src/org/commcare/views/widgets/ImageWidget.java
Labels: product/invisible

#2418 Added new translation
  app/assets/locales/android_translatable_strings.txt
Labels: product/all-users

#2420 Bug Fix: XpathException in End of Form linking crashes CommCare
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: bug, product/all-users, ready for review

#2411 Text to speech support
  app/assets/locales/android_translatable_strings.txt
  app/res/drawable/ic_tts.xml
  app/res/layout/media_layout.xml
  app/res/xml/main_preferences.xml
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/preferences/MainConfigurablePreferences.java
  app/src/org/commcare/tts/TextToSpeechCallback.kt
  app/src/org/commcare/tts/TextToSpeechConverter.kt
  app/src/org/commcare/views/media/MediaLayout.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: Release Note, product/all-users

#2412 Launch Session endpoints from Intent
  app/res/values/strings.xml
  app/src/org/commcare/activities/DispatchActivity.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/models/AndroidSessionWrapper.java
  app/src/org/commcare/utils/AndroidUtil.java
  app/unit-tests/resources/commcare-apps/index_and_cache_test/suite.xml
  app/unit-tests/src/org/commcare/android/tests/navigation/ExternalLaunchTests.kt
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: cross requested, product/custom, ready for review

#2419 Android App Tests for New Query Prompt Defaults
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/QueryRequestActivity.java
  app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
  app/unit-tests/resources/commcare-apps/case_search_and_claim/user_restore.xml
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
  app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
Labels: cross requested, product/invisible, ready for review

#2416 Remove header from menu list
  app/instrumentation-tests/src/org/commcare/androidTests/FormAttachmentUploadTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/SavedFormTest.java
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
  app/res/layout/menu_list_header.xml
  app/src/org/commcare/activities/components/MenuList.java
Labels: minor (quick review), product/all-users

#2417 Operate on hintText view only when it's non null
  app/src/org/commcare/views/QuestionsView.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: bug, product/all-users
