Repository dimagi/commcare-android, pull requests merged in 2020-09, with the labels that each got.

#2338 [2.48.10 hotfix] Update retry time overflow fix
  app/AndroidManifest.xml
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
Labels: critical-bug-fix, product/all-users, ready for review

#2280 Adds support for tiered lists and barcode scan in Case Claim prompts
  app/res/layout/http_request_layout.xml
  app/res/layout/query_prompt_layout.xml
  app/src/org/commcare/activities/QueryRequestActivity.java
  app/src/org/commcare/engine/cases/CaseUtils.java
  app/unit-tests/resources/commcare-apps/case_search_and_claim/default/app_strings.txt
  app/unit-tests/resources/commcare-apps/case_search_and_claim/fixtures.xml
  app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
  app/unit-tests/src/org/commcare/android/mocks/ModernHttpRequesterMock.java
  app/unit-tests/src/org/commcare/android/tests/activities/PostRequestActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
  app/unit-tests/src/org/commcare/android/util/TestAppInstaller.java
Labels: product/all-users, ready for review

#2337 Changes in Mobile Priviliges Navigation
  app/assets/locales/android_startup_strings.txt
  app/assets/locales/android_translatable_strings.txt
  app/res/xml/app_manager_developer_preferences.xml
  app/res/xml/app_manager_preferences.xml
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/activities/AppManagerActivity.java
  app/src/org/commcare/activities/CommCarePreferenceActivity.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/preferences/AppManagerAdvancedPreferences.java
  app/src/org/commcare/preferences/AppManagerDeveloperPreferences.java
  app/src/org/commcare/preferences/DeveloperPreferences.java
  app/src/org/commcare/views/dialogs/DialogCreationHelpers.java
Labels: product/all-users

#2340 Increase no of allowed apps to 4
  app/src/org/commcare/activities/CommCareSetupActivity.java
Labels: product/all-users, ready for review

#2294 Update firebase services dependencies
  app/build.gradle
  build.gradle
Labels: minor (quick review), product/invisible

#2335 Looks for a missing resource in All resources
  app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
  app/src/org/commcare/models/database/SqlStorage.java
Labels: product/invisible, ready for review

#2266 Markdown update with support for Tables
  app/build.gradle
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/utils/MarkupUtil.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: product/all-users, ready for review

#2322 Implements request age and source in Install requests headers
  app/build.gradle
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/android/javarosa/AndroidXFormHttpRequester.java
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/android/resource/installers/MediaFileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
  app/src/org/commcare/engine/references/JavaHttpReference.java
  app/src/org/commcare/engine/references/ParameterizedReference.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/interfaces/CommcareRequestEndpoints.java
  app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
  app/src/org/commcare/network/CommcareRequestEndpointsMock.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
  app/src/org/commcare/network/RequestStats.kt
  app/src/org/commcare/tasks/ResourceEngineTask.java
  app/src/org/commcare/tasks/ResourceRecoveryTask.java
  app/src/org/commcare/update/UpdateHelper.java
  app/src/org/commcare/update/UpdateTask.java
  app/src/org/commcare/update/UpdateWorker.kt
  app/src/org/commcare/utils/DummyResourceTable.java
  app/src/org/commcare/utils/TimeProvider.kt
  app/src/org/commcare/views/media/AudioPlaybackButtonBase.java
  app/src/org/commcare/views/media/MediaLayout.java
  app/unit-tests/resources/commcare-apps/update_tests/valid_update_with_lazy_multimedia_present/commcare/image/data/question1.jpg
  app/unit-tests/resources/commcare-apps/update_tests/valid_update_with_lazy_multimedia_present/default/app_strings.txt
  app/unit-tests/resources/commcare-apps/update_tests/valid_update_with_lazy_multimedia_present/en/app_strings.txt
  app/unit-tests/resources/commcare-apps/update_tests/valid_update_with_lazy_multimedia_present/media_suite.xml
  app/unit-tests/resources/commcare-apps/update_tests/valid_update_with_lazy_multimedia_present/modules-0/forms-0.xml
  app/unit-tests/resources/commcare-apps/update_tests/valid_update_with_lazy_multimedia_present/modules-0/forms-1.xml
  app/unit-tests/resources/commcare-apps/update_tests/valid_update_with_lazy_multimedia_present/profile.ccpr
  app/unit-tests/resources/commcare-apps/update_tests/valid_update_with_lazy_multimedia_present/suite.xml
  app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java
  app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.kt
  app/unit-tests/src/org/commcare/mediadownload/LazyMediaDownloadTest.kt
  app/unit-tests/src/org/commcare/update/UpdateWorkerTest.kt
Labels: cross requested, product/invisible

#2336 Inflate MediaLayout using xml [WIP]
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/res/layout/media_layout.xml
  app/res/layout/missing_media_view.xml
  app/res/values/dimens.xml
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/views/ResizingImageView.java
  app/src/org/commcare/views/media/CommCareVideoView.java
  app/src/org/commcare/views/media/MediaLayout.java
  app/src/org/commcare/views/widgets/SelectOneAutoAdvanceWidget.java
Labels: product/all-users, ready for review

#2343 Replace spongycastle to bouncycastle in proguard
  app/proguard.cfg
Labels: critical-bug-fix, minor (quick review), product/invisible

#2344 Fix radio button visibility
  app/src/org/commcare/views/widgets/SelectOneAutoAdvanceWidget.java
Labels: critical-bug-fix, minor (quick review), product/invisible

#2346 Improve audio widget placeholder text
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/views/widgets/CommCareAudioWidget.java
Labels: enhancement, minor (quick review), product/all-users

#2347 Fix long standing bug with varying update frequency prompt
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/heartbeat/UpdatePromptHelper.java
Labels: bug, product/invisible

#2348 Corrects multiple app limit message
  app/res/layout/multiple_apps_limit_view.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/MultipleAppsLimitWarningActivity.java
Labels: bug, minor (quick review), product/invisible

#2349 Fixes XForm Uninstall
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Labels: bug, product/invisible, ready for review

#2350 fix update completion indicator in case of background update
  app/src/org/commcare/activities/UpdateActivity.java
Labels: product/invisible, ready for review

#2352 Fix info visibility when markers are too close
  app/src/org/commcare/gis/EntityMapboxActivity.kt
Labels: bug, product/all-users

#2351 Orphan Progress dialog fix
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/activities/UpdateActivity.java
  app/src/org/commcare/provider/ExternalApiReceiver.java
  app/src/org/commcare/tasks/templates/CommCareTask.java
  app/src/org/commcare/tasks/templates/CommCareTaskConnector.java
  app/src/org/commcare/views/dialogs/DialogController.java
  app/unit-tests/src/org/commcare/activities/DataPullControllerMock.java
  app/unit-tests/src/org/commcare/android/mocks/CommCareTaskConnectorFake.java
Labels: bug, product/invisible, ready for review

#2353 Lazy Media fixes
  app/build.gradle
  app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
  app/src/org/commcare/views/media/MediaLayout.java
  app/unit-tests/src/org/commcare/mediadownload/LazyMediaDownloadTest.kt
  app/unit-tests/src/org/commcare/rules/MainCoroutineRule.kt
Labels: product/invisible, ready for review

#2354 Fix audio button clipping on small devices
  app/res/layout/audio_prototype.xml
Labels: bug, minor (quick review), product/all-users

#2356 Use RelativeLayout instead of ConstraintLayout for mediaview
  app/build.gradle
  app/res/layout/media_layout.xml
  app/res/layout/missing_media_view.xml
  app/src/org/commcare/views/media/MediaLayout.java
Labels: product/all-users, ready for review

#2360 Temporarily switch to using apk in browserstack
  scripts/browserstack.py
Labels: minor (quick review), product/invisible

#2357 Backmerge Commcare 2.50
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/proguard.cfg
  app/res/layout/audio_prototype.xml
  app/res/layout/media_layout.xml
  app/res/layout/missing_media_view.xml
  app/res/layout/multiple_apps_limit_view.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/MultipleAppsLimitWarningActivity.java
  app/src/org/commcare/activities/UpdateActivity.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/gis/EntityMapboxActivity.kt
  app/src/org/commcare/heartbeat/UpdatePromptHelper.java
  app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
  app/src/org/commcare/provider/ExternalApiReceiver.java
  app/src/org/commcare/tasks/templates/CommCareTask.java
  app/src/org/commcare/tasks/templates/CommCareTaskConnector.java
  app/src/org/commcare/views/dialogs/DialogController.java
  app/src/org/commcare/views/media/MediaLayout.java
  app/src/org/commcare/views/widgets/CommCareAudioWidget.java
  app/src/org/commcare/views/widgets/SelectOneAutoAdvanceWidget.java
  app/unit-tests/src/org/commcare/activities/DataPullControllerMock.java
  app/unit-tests/src/org/commcare/android/mocks/CommCareTaskConnectorFake.java
  app/unit-tests/src/org/commcare/mediadownload/LazyMediaDownloadTest.kt
  app/unit-tests/src/org/commcare/rules/MainCoroutineRule.kt
Labels: product/invisible

#2358 Add fixtures test
  app/instrumentation-tests/resources/fixtures.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/FixturesTest.kt
Labels: product/invisible, ready for review

#2362 Add Menu tests
  app/instrumentation-tests/resources/settings_sheet_tests.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/MenuTests.kt
Labels: product/invisible, ready for review
