Repository dimagi/commcare-android, pull requests merged in 2020-02, with the labels that each got.

#2182 Adds translation key for cancel button on Pin Screen
  app/assets/locales/android_translatable_strings.txt
  app/res/layout/pin_screen_buttons.xml
  app/src/org/commcare/activities/CreatePinActivity.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2179 Restrict event logging if the video is never played
  app/src/org/commcare/views/media/MediaLayout.java
Labels: minor (quick review), product/invisible

#2176 Update app to target Android 10
  app/AndroidManifest.xml
  app/build.gradle
  app/src/org/commcare/AndroidPreferenceManager.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/LoginActivityUIController.java
  app/src/org/commcare/activities/MultimediaInflaterActivity.java
  app/src/org/commcare/activities/UITestInfoActivity.java
  app/src/org/commcare/activities/components/FormEntryInstanceState.java
  app/src/org/commcare/activities/components/FormLayoutHelpers.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/recovery/measures/ScanCczTask.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/tasks/FormLoaderTask.java
  app/src/org/commcare/utils/DeviceIdentifier.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/utils/UnsupportedMediaException.java
  app/src/org/commcare/views/QuestionsView.java
  app/src/org/commcare/views/widgets/MediaWidget.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
Labels: product/all-users, ready for review

#2186 Fixes form load crash in case of an pending update
  app/src/org/commcare/activities/components/FormEntryInstanceState.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Labels: critical-bug-fix, product/all-users, ready for review

#2187 Deregisters forms on uninstall
  app/src/org/commcare/android/database/app/models/FormDefRecord.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
Labels: bug, product/invisible, ready for review
