Repository dimagi/commcare-android, pull requests merged in 2020-08, with the labels that each got.

#2293 Adding orientation change support to gregorian date widget
  app/res/layout/scrolling_calendar_widget.xml
  app/src/org/commcare/views/widgets/CalendarFragment.java
  app/src/org/commcare/views/widgets/GregorianDateWidget.java
Labels: product/all-users, ready for review

#2305 Add idling resource to avoid AppNotIdleExceptions
  app/instrumentation-tests/src/org/commcare/CommCareInstrumentationTestApplication.java
  app/instrumentation-tests/src/org/commcare/androidTests/AsyncRestoreTest.java
  app/instrumentation-tests/src/org/commcare/utils/ProgressIdlingResource.kt
Labels: minor (quick review), product/invisible

#2307 [2.49.5 hotfix] Fix Update Resumptions
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/logging/analytics/UpdateStats.java
Labels: product/all-users, ready for review

#2301 Removes ForceTLS12BuilderConfig
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/network/ForceTLS12BuilderConfig.java
Labels: bug, product/invisible

#2306 Better error message when wrong app install code is used
  app/assets/locales/android_startup_strings.txt
  app/src/org/commcare/activities/CommCareSetupActivity.java
Labels: cross requested, minor (quick review), product/all-users

#2308 Update fixes Port for LTS [2.48.10 hotfix]
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/logging/analytics/UpdateStats.java
Labels: product/all-users

#2304 Only allow the Entity List Action button to be clicked once
  app/src/org/commcare/models/AndroidSessionWrapper.java
  app/src/org/commcare/views/EntityActionViewUtils.java
Labels: bug, product/invisible

#2295 Fixes for Lazy Media Download
  app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
  app/src/org/commcare/mediadownload/MissingMediaDownloadResult.kt
  app/src/org/commcare/mediadownload/MissingMediaDownloadWorker.kt
Labels: bug, product/invisible, ready for review

#2292 Use dev pref for file oversize warning setting
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: minor (quick review), product/all-users

#2310 Commcare 2.49.5 backmerge
  app/AndroidManifest.xml
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/logging/analytics/UpdateStats.java
Labels: product/invisible

#2309 Remove recovery activity from backstack on launching app manager
  app/src/org/commcare/activities/RecoveryActivity.java
Labels: product/invisible, ready for review

#2312 [2.49.6] Fixes Auto update retries
  app/src/org/commcare/update/UpdateWorker.kt
Labels: bug, product/all-users, ready for review

#2313 Move to Android Junit Test Runner for Unit tests
  app/build.gradle
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/update/UpdateWorker.kt
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
  app/unit-tests/src/org/commcare/android/CommCareTestRunner.java
  app/unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java
  app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java
  app/unit-tests/src/org/commcare/android/tests/GraphTest.java
  app/unit-tests/src/org/commcare/android/tests/HeartbeatAndPromptedUpdateTests.java
  app/unit-tests/src/org/commcare/android/tests/ImageInflationTest.java
  app/unit-tests/src/org/commcare/android/tests/IndexSpanningIteratorTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/CommCareSetupActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/FormRecordListActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/MultimediaInflaterActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/PostRequestActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/UpdateActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/application/AppInitializationTest.java
  app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java
  app/unit-tests/src/org/commcare/android/tests/application/PendingCalcTest.java
  app/unit-tests/src/org/commcare/android/tests/caselist/EntityListCacheIndexTest.java
  app/unit-tests/src/org/commcare/android/tests/caselist/EntityListCalloutDataTest.java
  app/unit-tests/src/org/commcare/android/tests/database/SqlStorageBaseTests.java
  app/unit-tests/src/org/commcare/android/tests/formentry/FormIntentTests.java
  app/unit-tests/src/org/commcare/android/tests/formentry/FormWidgetTests.java
  app/unit-tests/src/org/commcare/android/tests/formentry/IntentCalloutTests.java
  app/unit-tests/src/org/commcare/android/tests/formnav/CalendarLocaleTest.java
  app/unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java
  app/unit-tests/src/org/commcare/android/tests/formsave/FormRecordProcessingTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/ArchivedFormPurgeTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/FixtureLoadingTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/KeyRecordTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/ProcessingTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/UnsentFormsTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/XFormUpdateInfoTest.java
  app/unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java
  app/unit-tests/src/org/commcare/android/tests/queries/ExpressionCacheTest.java
  app/unit-tests/src/org/commcare/android/tests/queries/LedgerDbQueryTest.java
  app/unit-tests/src/org/commcare/logging/DataChangeLoggerTest.java
  app/unit-tests/src/org/commcare/models/database/HybridFileBackedSqlStorageTest.java
  app/unit-tests/src/org/commcare/models/database/StoreFixturesOnFilesystemTests.java
  app/unit-tests/src/org/commcare/notifications/NotificationMessageTest.java
  app/unit-tests/src/org/commcare/recovery/measures/RecoveryMeasuresTest.java
  app/unit-tests/src/org/commcare/utils/FormCacheEligibilityTester.java
Labels: product/invisible

#2314 Add project name to test builds on browserstack
  scripts/browserstack.py
Labels: minor (quick review), product/invisible

#2317 Backmerge Commcare 2.49.6
  app/src/org/commcare/update/UpdateWorker.kt
Labels: product/invisible

#2316 Use testBuildType field in gradle-property
  app/build.gradle
Labels: minor (quick review), product/invisible

#2318 Add jacoco code coverage plugin
  app/build.gradle
  app/jacoco.gradle
  build.gradle
Labels: product/invisible

#2320 [2.49.7 hotfix] Fix to current location for Maps Location Capture
  app/res/values/strings.xml
  app/src/org/commcare/activities/GeoPointMapActivity.java
Labels: product/all-users

#2323 comment about changes in mm extensions
  app/src/org/commcare/utils/FormUploadUtil.java
Labels: product/invisible

#2324 null adapter check in menu to avoid NPE
  app/src/org/commcare/activities/FormRecordListActivity.java
Labels: product/invisible

#2326 Show downloaded app update info in case of no internet
  app/src/org/commcare/activities/UpdateActivity.java
Labels: minor (quick review), product/all-users

#2327 Backmerge Commcare 2.49.7
  app/res/values/strings.xml
  app/src/org/commcare/activities/GeoPointMapActivity.java
Labels: product/invisible

#2299 Add more tests from calabash to espresso
  app/build.gradle
  app/instrumentation-tests/resources/app_update.ccz
  app/instrumentation-tests/resources/extended_cities_table.xlsx
  app/instrumentation-tests/resources/initial_cities_table.xlsx
  app/instrumentation-tests/resources/invalid_index_app.ccz
  app/instrumentation-tests/src/org/commcare/CommCareInstrumentationTestApplication.java
  app/instrumentation-tests/src/org/commcare/androidTests/AppUpdateTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/AsyncRestoreTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/CaseClaimTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/InstallFromListTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LookupTableTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SavedFormTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/SubmissionErrorResponseTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SyncRecoveryTest.kt
  app/instrumentation-tests/src/org/commcare/utils/CustomMatchers.kt
  app/instrumentation-tests/src/org/commcare/utils/HQApi.java
  app/instrumentation-tests/src/org/commcare/utils/InputStreamRequestBody.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.java
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
  app/instrumentation-tests/src/org/commcare/utils/ViewInteraction+Extension.kt
  app/proguard.cfg
  scripts/browserstack.py
Labels: product/invisible, ready for review

#2329 Add analytics for in-app updates
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
Labels: minor (quick review), product/invisible

#2331 Remove AppUpdateTest to pass builds
  app/instrumentation-tests/src/org/commcare/androidTests/AppUpdateTest.kt
Labels: minor (quick review), product/invisible

#2311 Change spongycastle to bouncycastle
  app/build.gradle
  app/libs/android-zebra-interface-1.1.aar
  app/src/org/commcare/utils/SigningUtil.java
Labels: product/internal-or-flagged, ready for review

#2332 Use BuildConfig to get version name
  app/src/org/commcare/android/logging/ReportingUtils.java
Labels: bug, minor (quick review), product/all-users

#2330 Fix audio recorder filename
  app/src/org/commcare/views/widgets/CommCareAudioWidget.java
  app/src/org/commcare/views/widgets/RecordingFragment.java
Labels: minor (quick review), product/invisible

#2333 Better log tag for AppUpdateManager
  app/src/org/commcare/appupdate/CommcareFlexibleAppUpdateManager.java
  app/src/org/commcare/appupdate/CommcareImmediateAppUpdateManager.java
Labels: minor (quick review), product/invisible

#2334 Revert removing kujaku network change receiver
  app/AndroidManifest.xml
Labels: minor (quick review), product/invisible
