Repository dimagi/commcare-android, pull requests merged in 2020-04, with the labels that each got.

#2203 Commcare 2.48.2 Backmerge
  app/AndroidManifest.xml
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/preferences/HiddenPreferences.java
Labels: product/invisible, ready for review

#2205 Fix "Choose point on Map" functionality
  app/src/org/commcare/views/widgets/GeoPointWidget.java
Labels: bug, product/invisible

#2207 GPS Maps: Focuses on last selected location
  app/src/org/commcare/activities/GeoPointMapActivity.java
  app/src/org/commcare/views/widgets/GeoPointWidget.java
Labels: minor (quick review), product/all-users

#2209 GPS: Only update location in case of better accuracy from Updates
  app/src/org/commcare/activities/GeoPointMapActivity.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2208 GPS Maps: Adds Layer change Button
  app/res/drawable-anydpi/ic_layers.xml
  app/res/layout/geopoint_layout.xml
  app/res/values/colors.xml
  app/res/values/dimens.xml
  app/src/org/commcare/activities/GeoPointMapActivity.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/utils/GeoUtils.java
  app/src/org/commcare/utils/MapLayer.java
Labels: minor (quick review), product/all-users, ready for review

#2210 backmerge Commcare 2.48.4
  app/src/org/commcare/activities/GeoPointMapActivity.java
Labels: product/invisible

#2212 Fix for NPE while De-regestering Form
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
Labels: bug, product/invisible, ready for review

#2214 Update fabric to the latest version
  app/build.gradle
  build.gradle
Labels: minor (quick review), product/invisible

#2215 Backmerge Commcare 2.48
  app/build.gradle
  build.gradle
Labels: product/invisible

#2219 Fabric debug crash - The Crashlytics build ID is missing
  app/AndroidManifest.xml
Labels: bug, product/invisible, ready for review

#2220 Assist Crash reports with device logs
  app/src/org/commcare/logging/AndroidLogger.java
Labels: product/invisible, ready for review

#2206 Show detailed error for captive portal presense
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
  app/src/org/commcare/network/HttpCalloutTask.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/ManageKeyRecordTask.java
  app/src/org/commcare/tasks/ProcessAndSendTask.java
  app/src/org/commcare/tasks/ResourceEngineTask.java
  app/src/org/commcare/utils/FormUploadResult.java
  app/src/org/commcare/utils/FormUploadUtil.java
  app/src/org/commcare/views/notifications/NotificationMessageFactory.java
Labels: cross requested, product/all-users, ready for review

#2221 Label required questions with a red asterisk
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: product/internal-or-flagged, ready for review

#2222 Fix NPE while building question label with asterisk
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: critical-bug-fix, minor (quick review), product/internal-or-flagged

#2224 Disable minify, proguard for debug builds
  app/build.gradle
Labels: minor (quick review), product/invisible, ready for review

#2223 Fix unwanted onItemSelected callback in spinner
  app/src/org/commcare/views/widgets/SpinnerWidget.java
Labels: bug, minor (quick review), product/all-users, ready for review

#2225 Stop users from using app when forced update is required
  app/src/org/commcare/heartbeat/UpdatePromptHelper.java
Labels: bug, minor (quick review), product/all-users, ready for review

#2216 Add support for in-app updates
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/src/org/commcare/activities/HomeNavDrawerController.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/PromptActivity.java
  app/src/org/commcare/activities/PromptApkUpdateActivity.java
  app/src/org/commcare/activities/RootMenuHomeActivity.java
  app/src/org/commcare/activities/StandardHomeActivity.java
  app/src/org/commcare/appupdate/AppUpdateController.java
  app/src/org/commcare/appupdate/AppUpdateControllerFactory.java
  app/src/org/commcare/appupdate/AppUpdateState.java
  app/src/org/commcare/appupdate/CommcareFlexibleAppUpdateManager.java
  app/src/org/commcare/appupdate/CommcareImmediateAppUpdateManager.java
  app/src/org/commcare/appupdate/DummyFlexibleAppUpdateManager.java
  app/src/org/commcare/appupdate/FlexibleAppUpdateController.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/views/notifications/NotificationMessageFactory.java
Labels: Release Note, cross requested, product/all-users, ready for review

#2228 Fixes testAllExternalizablesInPrototypeFactory
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: bug, minor (quick review), product/invisible, ready for review

#2227 Show PromptAPK activity for version mismatch error
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/PromptActivity.java
  app/src/org/commcare/activities/PromptApkUpdateActivity.java
Labels: product/all-users, ready for review
