Repository dimagi/commcare-android, pull requests merged in 2020-10, with the labels that each got.

#2361 Add form entry tests
  app/instrumentation-tests/resources/languages.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/FormEntryTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SavedFormTest.java
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
Labels: product/invisible, ready for review

#2364 Remove KujakuNetworkChangeReceiver
  app/AndroidManifest.xml
Labels: critical-bug-fix, minor (quick review), product/all-users

#2366 include original exception as cause
  app/src/org/commcare/android/database/user/models/FormRecord.java
Labels: cross requested, product/invisible

#2369 Backmerge Commcare 2.50.1
  app/AndroidManifest.xml
  app/src/org/commcare/android/database/user/models/FormRecord.java
Labels: product/invisible

#2368 Removes default flags for RefreshToLatestBuildReceiver
  app/AndroidManifest.xml
Labels: product/invisible

#2370 Fix for login using PIN when no User exists for a UserKeyRecord
  app/src/org/commcare/activities/DataPullController.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/tasks/ManageKeyRecordTask.java
  app/unit-tests/src/org/commcare/activities/DataPullControllerMock.java
Labels: bug, product/all-users, ready for review

#2376 Adds label to cancel button In Reset Pin UI
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/activities/PinAuthenticationActivity.java
Labels: product/internal-or-flagged, ready for review

#2378 Broadcasts Case updates to Reminders app
  app/AndroidManifest.xml
  app/src/org/commcare/models/FormRecordProcessor.java
Labels: product/invisible

#2372 Use flexible font size for label and list widgets
  app/src/org/commcare/views/widgets/LabelWidget.java
  app/src/org/commcare/views/widgets/ListMultiWidget.java
  app/src/org/commcare/views/widgets/ListWidget.java
Labels: bug, minor (quick review), product/all-users

#2381 Remove form entry test sync temporarily
  app/instrumentation-tests/src/org/commcare/androidTests/FormEntryTest.kt
Labels: minor (quick review), product/invisible

#2379 Add form settings test
  app/instrumentation-tests/src/org/commcare/androidTests/FormSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/utils/CustomMatchers.kt
Labels: minor (quick review), product/invisible

#2373 Block Users on Rooted Devices
  app/build.gradle
  app/res/values/strings.xml
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/preferences/HiddenPreferences.java
Labels: product/internal-or-flagged

#2384 Add option to re-run failing espresso tests
  scripts/browserstack.py
Labels: minor (quick review), product/invisible

#2385 [2.48.11] Delete raw images from Saved Forms
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/DiskUtils.kt
  app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/tasks/CleanRawMedia.kt
  app/src/org/commcare/utils/StorageUtils.java
Labels: product/internal-or-flagged

#2371 Add RTL support to textview
  app/res/layout/form_filter_item.xml
  app/res/layout/menu_list_item_modern.xml
  app/res/layout/question_widget_text.xml
  app/res/layout/question_widget_text_compact.xml
  app/res/layout/screen_form_entry.xml
  app/src/org/commcare/views/ViewUtil.java
  app/src/org/commcare/views/widgets/LabelWidget.java
  app/src/org/commcare/views/widgets/ListMultiWidget.java
  app/src/org/commcare/views/widgets/ListWidget.java
Labels: product/all-users

#2386 Add settings test
  app/build.gradle
  app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
Labels: product/invisible

#2382 Add languages test
  app/instrumentation-tests/src/org/commcare/androidTests/AsyncRestoreTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/BaseTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/BaseTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/CaseClaimTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/FormAttachmentUploadTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/FormEntryTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LanguagesTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SavedFormTest.java
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
Labels: minor (quick review), product/invisible

#2387 Add select filter test
  app/instrumentation-tests/resources/test_select_filters.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/FormFilteringTest.kt
  app/instrumentation-tests/src/org/commcare/utils/Matcher+Extension.kt
Labels: minor (quick review), product/invisible

#2388 Add Tiles test
  app/instrumentation-tests/resources/tiles.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/FormFilteringTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/TilesTest.kt
  app/instrumentation-tests/src/org/commcare/utils/Array+Extension.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
  app/instrumentation-tests/src/org/commcare/utils/Matcher+Extension.kt
  app/proguard.cfg
Labels: product/invisible, ready for review

#2367 Add clear buttons to all questions with radio buttons
  app/src/org/commcare/views/widgets/SelectOneAutoAdvanceWidget.java
  app/src/org/commcare/views/widgets/SelectOneWidget.java
  app/src/org/commcare/views/widgets/WidgetUtils.java
Labels: product/all-users, ready for review

#2383 Add case list search and sort tests
  app/instrumentation-tests/resources/test_list_search.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/CaseListSearchTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/CaseListSortTest.kt
Labels: minor (quick review), product/invisible

#2391 Add dialog tests
  app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DialogTests.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LanguagesTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/MenuTests.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
Labels: product/invisible, ready for review

#2393 Add lookup table sorting test
  app/instrumentation-tests/resources/lookup_table_sort_test.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/LookupTableTest.kt
  app/instrumentation-tests/src/org/commcare/utils/CustomMatchers.kt
Labels: product/invisible, ready for review

#2392 Add demo user online and offline test
  app/instrumentation-tests/resources/demo_user_test_1.ccz
  app/instrumentation-tests/resources/demo_user_test_2.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/DemoUserOfflineTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DemoUserOnlineTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DemoUserTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FormEntryTest.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
Labels: product/invisible, ready for review

#2395 Add case sharing tests
  app/instrumentation-tests/resources/case_sharing.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/CaseSharingTest.kt
Labels: don't pull, product/invisible

#2394 Add log submission test
  app/AndroidManifest.xml
  app/instrumentation-tests/src/org/commcare/androidTests/LogSubmissionTest.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
  app/src/org/commcare/activities/UITestInfoActivity.java
  app/src/org/commcare/services/CommCareSessionService.java
Labels: product/invisible, ready for review
