Repository dimagi/commcare-android, pull requests merged in 2020-06, with the labels that each got.

#2255 Reverts firebase-ads to 16.0.1
  app/build.gradle
Labels: product/invisible

#2257 Use current form index to check constraints
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: bug, cross requested, product/internal-or-flagged

#2258 Corrects log setting values
  app/src/org/commcare/preferences/HiddenPreferences.java
Labels: product/invisible, ready for review

#2256 Add a button to clear radio button selection.
  app/assets/locales/android_translatable_strings.txt
  app/res/drawable/blue_outlined_view.xml
  app/res/layout/blue_outlined_button.xml
  app/src/org/commcare/views/widgets/SelectOneWidget.java
Labels: minor (quick review), product/all-users

#2261 Set latest CC version from Heartbeat response
  app/src/org/commcare/heartbeat/HeartbeatRequester.java
Labels: product/invisible

#2260 Default to current version while getting latestcommcareversion
  app/src/org/commcare/preferences/HiddenPreferences.java
Labels: critical-bug-fix, product/all-users

#2262 Draw boundary fixes
  app/res/layout/activity_drawing_boundary.xml
  app/src/org/commcare/gis/DrawingBoundaryActivity.kt
  app/src/org/commcare/gis/DrawingBoundaryActivityUIController.kt
Labels: product/invisible, ready for review

#2264 Updates area as user walk the boundary
  app/src/org/commcare/gis/DrawingBoundaryActivity.kt
Labels: bug, product/invisible

#2259 Keep update check button enabled all the time
  app/src/org/commcare/activities/UpdateUIController.java
Labels: minor (quick review), product/all-users

#2263 Adding all commcare files to primary dex
  app/build.gradle
  app/proguard-multidex.pro
  app/proguard.cfg
Labels: critical-bug-fix, product/all-users, ready for review

#2265 Corrects version to 2.50
  app/res/values/strings.xml
Labels: product/invisible

#2267 NPE fix on cancelling form submission task
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/sync/FormSubmissionHelper.java
Labels: product/invisible, ready for review

#2243 Adds lazy donwnload for multimedia for App Updates
  app/assets/locales/android_translatable_strings.txt
  app/res/layout/missing_media_view.xml
  app/res/values/strings.xml
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/CommCareVerificationActivity.java
  app/src/org/commcare/activities/UpdateActivity.java
  app/src/org/commcare/android/database/app/models/ResourceModelUpdater.java
  app/src/org/commcare/android/database/app/models/ResourceV13.java
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/android/resource/installers/MediaFileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstallerV8.java
  app/src/org/commcare/engine/resource/AndroidResourceTable.java
  app/src/org/commcare/engine/resource/AndroidResourceUtils.kt
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
  app/src/org/commcare/mediadownload/MissingMediaDownloadListener.kt
  app/src/org/commcare/mediadownload/MissingMediaDownloadResult.kt
  app/src/org/commcare/mediadownload/MissingMediaDownloadWorker.kt
  app/src/org/commcare/models/AndroidPrototypeFactoryV8.java
  app/src/org/commcare/models/database/DbUtil.java
  app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/tasks/VerificationTask.java
  app/src/org/commcare/utils/AndroidUtil.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/views/media/AudioPlaybackButtonBase.java
  app/src/org/commcare/views/media/MediaLayout.java
  app/src/org/commcare/views/media/MediaState.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: cross requested, don't pull, product/internal-or-flagged

#2269 Commcare 2.49 release
  app/build.gradle
  app/proguard-multidex.pro
  app/proguard.cfg
  app/res/layout/activity_drawing_boundary.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/gis/DrawingBoundaryActivity.kt
  app/src/org/commcare/gis/DrawingBoundaryActivityUIController.kt
  app/src/org/commcare/heartbeat/HeartbeatRequester.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/sync/FormSubmissionHelper.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: cross requested, product/invisible

#2270 Applies font size for group labels
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/activities/components/FormLayoutHelpers.java
  app/src/org/commcare/preferences/FormEntryPreferences.java
  app/src/org/commcare/views/QuestionsView.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: minor (quick review), product/all-users

#2273 [2.48.9 LTS Hotifix] OOM protection for writing update stats
  app/AndroidManifest.xml
  app/src/org/commcare/logging/analytics/UpdateStats.java
Labels: critical-bug-fix, product/all-users

#2275 [2.49.1 hotfix] Remove install stats exception logging from update stats
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/logging/analytics/InstallAttempts.java
  app/src/org/commcare/logging/analytics/UpdateStats.java
  app/src/org/commcare/tasks/InstallStagedUpdateTask.java
Labels: cross requested, product/all-users, ready for review

#2274 [2.48.9] Removes writes for update install stats
  app/src/org/commcare/logging/analytics/UpdateStats.java
Labels: product/invisible, ready for review

#2278 Backmerge Commcare 2.49.2
  app/AndroidManifest.xml
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/logging/analytics/InstallAttempts.java
  app/src/org/commcare/logging/analytics/UpdateStats.java
  app/src/org/commcare/tasks/InstallStagedUpdateTask.java
Labels: minor (quick review), product/invisible

#2283 Adds Retry button for Recovery
  app/res/layout/screen_recovery.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/RecoveryActivity.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/tasks/ResourceRecoveryTask.java
Labels: cross requested, product/all-users

#2285 Navigate form to failed question when form finishes
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: critical-bug-fix, minor (quick review), product/all-users
