Repository dimagi/commcare-android, pull requests merged in 2020-07, with the labels that each got.

#2286 Backmerge Commcare 2.49.4
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: product/internal-or-flagged

#2272 Remove leading space from android-translatables
  app/assets/locales/android_translatable_strings.txt
Labels: minor (quick review), product/invisible

#2279 Hides manual quarantine behind developer option
  app/assets/locales/android_translatable_strings.txt
  app/res/xml/advanced_actions.xml
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/preferences/AdvancedActionsPreferences.java
  app/src/org/commcare/sync/FormSubmissionHelper.java
Labels: product/all-users, ready for review

#2290 Shows localized error for invalid case property length errors
  app/res/values/strings.xml
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/utils/StringUtils.java
Labels: cross requested, product/all-users

#2289 Quarantines form records on form processing failures
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/models/FormRecordProcessor.java
  app/src/org/commcare/sync/FormSubmissionHelper.java
Labels: product/all-users

#2291 Adds the build profile Id as an user property for analytics
  app/src/org/commcare/android/logging/ReportingUtils.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
Labels: cross requested, product/invisible

#2288 Use in-built audio widget as default to record audio
  app/src/org/commcare/views/widgets/CommCareAudioWidget.java
  app/src/org/commcare/views/widgets/WidgetFactory.java
Labels: minor (quick review), product/all-users

#2231 Add instrumentation tests for saved form using espresso
  README.md
  app/build.gradle
  app/instrumentation-tests/AndroidManifest.xml
  app/instrumentation-tests/resources/case_claim.ccz
  app/instrumentation-tests/resources/integration_test_app.ccz
  app/instrumentation-tests/resources/testSavedForm.ccz
  app/instrumentation-tests/src/org/commcare/AsyncRestoreHelperMock.java
  app/instrumentation-tests/src/org/commcare/CommCareInstrumentationTestApplication.java
  app/instrumentation-tests/src/org/commcare/CommCareJUnitRunner.java
  app/instrumentation-tests/src/org/commcare/androidTests/AsyncRestoreTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/BaseTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/CaseClaimTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/FormAttachmentUploadTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/SavedFormTest.java
  app/instrumentation-tests/src/org/commcare/utils/HQApi.java
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.java
  app/proguard.cfg
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/DrawActivity.java
  app/src/org/commcare/tasks/DataPullTask.java
  scripts/browserstack.py
Labels: cross requested, product/internal-or-flagged, ready for review

#2296 Crash fix on resuming activity after application got killed in background
  app/src/org/commcare/activities/SessionAwareHelper.java
Labels: bug, product/invisible, ready for review

#2298 Not crash when a form record is not found in db during purge
  app/src/org/commcare/tasks/PurgeStaleArchivedFormsTask.java
Labels: bug, product/invisible

#2300 Handle actionable failures for restore on login screen
  app/src/org/commcare/activities/LoginActivity.java
Labels: bug, product/invisible, ready for review

#2297 Don't crash when no form is found in storage while XForm Uninstall
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Labels: bug, product/invisible

#2282 Use FusedLocation client for capturing location
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/GeoPointActivity.java
  app/src/org/commcare/activities/components/FormEntryConstants.java
  app/src/org/commcare/activities/components/FormEntryDialogs.java
  app/src/org/commcare/android/javarosa/PollSensorController.java
  app/src/org/commcare/location/CommCareFusedLocationController.kt
  app/src/org/commcare/location/CommCareLocationController.kt
  app/src/org/commcare/location/CommCareLocationControllerFactory.kt
  app/src/org/commcare/location/CommCareLocationListener.kt
  app/src/org/commcare/location/CommCareProviderLocationController.kt
  app/src/org/commcare/utils/GeoUtils.java
  app/src/org/commcare/utils/Permissions.java
Labels: enhancement, product/invisible
