Repository dimagi/commcare-android, pull requests merged in 2020-05, with the labels that each got.

#2195 Form submissions Scheduling
  app/AndroidManifest.xml
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/res/drawable-anydpi/ic_layers.xml
  app/res/layout/geopoint_layout.xml
  app/res/values/colors.xml
  app/res/values/dimens.xml
  app/res/values/strings.xml
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/FormAndDataSyncer.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/activities/GeoPointMapActivity.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/RecoveryActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/activities/components/FormEntryConstants.java
  app/src/org/commcare/activities/components/FormEntryDialogs.java
  app/src/org/commcare/activities/components/FormRelevancyUpdating.java
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/engine/references/JavaHttpReference.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/heartbeat/HeartbeatRequester.java
  app/src/org/commcare/logging/AndroidLogger.java
  app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
  app/src/org/commcare/network/HttpCalloutTask.java
  app/src/org/commcare/network/RateLimitedException.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/provider/ExternalApiReceiver.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/sync/CancellationChecker.java
  app/src/org/commcare/sync/FormSubmissionHelper.java
  app/src/org/commcare/sync/FormSubmissionProgressListener.java
  app/src/org/commcare/sync/FormSubmissionWorker.kt
  app/src/org/commcare/sync/ProcessAndSendTask.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/ManageKeyRecordTask.java
  app/src/org/commcare/tasks/ResourceEngineTask.java
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
  app/src/org/commcare/utils/FormUploadResult.java
  app/src/org/commcare/utils/FormUploadUtil.java
  app/src/org/commcare/utils/GeoUtils.java
  app/src/org/commcare/utils/MapLayer.java
  app/src/org/commcare/utils/PendingCalcs.java
  app/src/org/commcare/views/IncompleteFormRecordView.java
  app/src/org/commcare/views/notifications/NotificationMessageFactory.java
  app/src/org/commcare/views/widgets/GeoPointWidget.java
  app/src/org/commcare/views/widgets/ImageWidget.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
  app/unit-tests/src/org/commcare/android/mocks/FormAndDataSyncerFake.java
  build.gradle
Labels: product/invisible, ready for review

#2202 Rate limit error message improvement
  app/assets/locales/android_translatable_strings.txt
  app/res/xml/advanced_actions.xml
  app/src/org/commcare/activities/FormAndDataSyncer.java
  app/src/org/commcare/activities/RecoveryActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/preferences/AdvancedActionsPreferences.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/sync/FormSubmissionHelper.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/utils/FormUploadUtil.java
Labels: enhancement, product/all-users

#2229 Use normal update instead of forced for version mismatch exception
  app/src/org/commcare/activities/PromptApkUpdateActivity.java
  app/src/org/commcare/appupdate/AppUpdateControllerFactory.java
Labels: minor (quick review), product/internal-or-flagged

#2232 Fix position of context menu for android 7 devices
  app/res/values-v11/styles.xml
  app/res/values-v11/themes.xml
  app/res/values-v14/themes.xml
  app/res/values-v24/themes.xml
  app/res/values/styles.xml
  app/res/values/themes.xml
Labels: bug, product/all-users

#2234 Fix npe in deleting files inside directory
  app/src/org/commcare/utils/FileUtil.java
Labels: bug, minor (quick review), product/all-users

#2235 Hide menu options when required permissions are missing
  app/src/org/commcare/fragments/InstallPermissionsFragment.java
Labels: bug, minor (quick review), product/all-users

#2233 Show form-save-toast before finishing activity
  app/src/org/commcare/activities/FormEntryActivity.java
Labels: bug, minor (quick review), product/all-users

#2236 Log events when intent.getData returns null and prevent npe
  app/src/org/commcare/activities/FormEntryActivity.java
Labels: minor (quick review), product/internal-or-flagged

#2240 allow tls 1.2 on Android 19
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/network/ForceTLS12BuilderConfig.java
  app/src/org/commcare/network/Tls12SocketFactory.java
Labels: product/invisible

#2242 [hotfix] Introduce Conscrypt security layer for API16-19
  app/build.gradle
  app/src/org/commcare/CommCareApplication.java
Labels: product/invisible

#2238 Use a separate form index to loop over all questions while saving form
  app/src/org/commcare/tasks/SaveToDiskTask.java
Labels: bug, product/invisible

#2244 [Hotfix] Update resets
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/engine/resource/ResourceInstallUtils.java
  app/src/org/commcare/logging/analytics/UpdateStats.java
  app/src/org/commcare/tasks/UpdateTask.java
Labels: Release Note, product/invisible, ready for review

#2247 Fixes testUpdateToAppMissingMultimedia
  app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java
Labels: cross requested, product/invisible, ready for review

#2239 Permit tls 1.2 on Android 19
  app/build.gradle
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/network/ForceTLS12BuilderConfig.java
  app/src/org/commcare/network/Tls12SocketFactory.java
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
Labels: cross requested, product/invisible

#2183 Upgrade to the Firebase Crashlytics SDK
  app/AndroidManifest.xml
  app/build.gradle
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/utils/CrashUtil.java
  build.gradle
Labels: product/invisible, ready for review

#2248 Improvements to Update Error handling
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/android/resource/installers/OfflineUserRestoreAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
  app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/engine/resource/ResourceInstallUtils.java
  app/src/org/commcare/logging/analytics/UpdateStats.java
  app/src/org/commcare/update/UpdateHelper.java
  app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java
Labels: cross requested, product/invisible, ready for review

#2250 Change APP_install analytics event name
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
Labels: minor (quick review), product/invisible

#2237 Adds Mapbox based Case list view and Area Mapper
  app/AndroidManifest.xml
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/res/color/button_colored_text.xml
  app/res/drawable-anydpi/ic_place.xml
  app/res/drawable/button_green_background.xml
  app/res/drawable/button_orange_background.xml
  app/res/drawable/button_red_background.xml
  app/res/layout/activity_drawing_boundary.xml
  app/res/layout/activity_entity_kujaku_map_info_view.xml
  app/res/layout/activity_entity_mapbox.xml
  app/res/values/colors.xml
  app/res/values/dimens.xml
  app/res/values/strings.xml
  app/res/values/styles.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/DotsEntryActivity.java
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/gis/AreaCalculator.kt
  app/src/org/commcare/gis/BaseMapboxActivity.kt
  app/src/org/commcare/gis/DrawingBoundaryActivity.kt
  app/src/org/commcare/gis/DrawingBoundaryActivityUIController.kt
  app/src/org/commcare/gis/EntityMapActivity.java
  app/src/org/commcare/gis/EntityMapUtils.kt
  app/src/org/commcare/gis/EntityMapboxActivity.kt
  app/src/org/commcare/gis/MapEntity.kt
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/utils/MediaUtil.java
  app/src/org/commcare/views/EntityView.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: cross requested, product/all-users, ready for review

#2251 Prevent resource leak in datapull response
  app/src/org/commcare/network/DataPullResponseFactory.java
  app/src/org/commcare/network/RemoteDataPullResponse.java
Labels: product/internal-or-flagged, ready for review

#2252 Adds minimal platform version
  app/res/values/strings.xml
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/utils/AndroidCommCarePlatform.java
  app/unit-tests/src/org/commcare/android/database/user/models/SessionStateDescriptorTests.java
Labels: product/all-users, ready for review

#2246 Defaults to a static version code for debug builds
  app/build.gradle
Labels: minor (quick review), product/invisible, ready for review

#2253 Updates to AGP 4.0, Gradle 6
  app/build.gradle
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: product/invisible

#2254 Determines Install Authority based on Profile Reference
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/engine/resource/AppInstallStatus.java
  app/src/org/commcare/engine/resource/installers/SingleAppInstallation.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresActivity.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresPresenter.java
  app/src/org/commcare/tasks/ResourceEngineListener.java
  app/src/org/commcare/tasks/ResourceEngineTask.java
  app/unit-tests/src/org/commcare/android/util/TestAppInstaller.java
Labels: product/invisible, ready for review
