Repository dimagi/commcare-android, pull requests merged in 2020-01, with the labels that each got.

#2161 Adds Video Usage analytics
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/StandardHomeActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/android/logging/ReportingUtils.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/google/services/analytics/FormAnalyticsHelper.kt
  app/src/org/commcare/logging/analytics/UpdateStats.java
  app/src/org/commcare/logic/AndroidFormController.java
  app/src/org/commcare/tasks/UpdateTask.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/views/media/MediaLayout.java
Labels: product/invisible, ready for review

#2158 Enable cleartext support by default
  app/AndroidManifest.xml
Labels: bug, minor (quick review), product/internal-or-flagged, ready for review

#2162 Return empty string as answer instead of OK for a label
  app/src/org/commcare/views/widgets/TriggerWidget.java
Labels: bug, product/all-users, ready for review

#2163 Add Portugese translation for buttons in App Management Screen
  app/res/values-pt/strings.xml
Labels: minor (quick review), product/invisible

#2159 Show error popup when hint text gets type mismatch exception
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/views/QuestionsView.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: bug, product/all-users, ready for review

#2164 Use downsampled banner to prevent OOM Exceptions
  app/src/org/commcare/activities/LoginActivityUIController.java
  app/src/org/commcare/adapters/HomeScreenAdapter.java
  app/src/org/commcare/views/CustomBanner.java
Labels: critical-bug-fix, product/all-users, ready for review

#2165 Revert "Return empty string as answer instead of OK for a label"
  app/src/org/commcare/views/widgets/TriggerWidget.java
Labels: minor (quick review), product/invisible

#2167 Unit tests for label widget
  app/unit-tests/resources/commcare-apps/form_entry_widgets/default/app_strings.txt
  app/unit-tests/resources/commcare-apps/form_entry_widgets/en/app_strings.txt
  app/unit-tests/resources/commcare-apps/form_entry_widgets/modules-0/forms-0.xml
  app/unit-tests/resources/commcare-apps/form_entry_widgets/profile.ccpr
  app/unit-tests/resources/commcare-apps/form_entry_widgets/suite.xml
  app/unit-tests/src/org/commcare/android/tests/formentry/FormWidgetTests.java
Labels: minor (quick review), product/invisible, ready for review

#2170 [Hotfix] Add days since last sync param to sync requests
  app/src/org/commcare/network/CommcareRequestGenerator.java
  app/src/org/commcare/utils/SyncDetailCalculations.java
  app/unit-tests/src/org/commcare/utils/DateUtilTest.java
Labels: minor (quick review), product/invisible, ready for review

#2169 Add days since last sync param to sync requests
  app/src/org/commcare/network/CommcareRequestGenerator.java
  app/src/org/commcare/utils/SyncDetailCalculations.java
  app/unit-tests/src/org/commcare/utils/DateUtilTest.java
Labels: don't pull, minor (quick review), product/invisible, ready for review

#2172 Add analytics for inline video usage
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/views/media/CommCareVideoView.java
  app/src/org/commcare/views/media/MediaLayout.java
Labels: product/invisible, ready for review

#2173 [HOTFIX] Fixes NPE with UCR v2
  app/src/org/commcare/engine/cases/AndroidIndexedFixtureInstanceTreeElement.java
Labels: critical-bug-fix, minor (quick review), product/invisible, ready for review

#2175 Use right username to validate if an update is blocked before login
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/UpdateActivity.java
  app/src/org/commcare/utils/SyncDetailCalculations.java
Labels: bug, product/invisible, ready for review

#2181 Port Android Pie changes for LTS
  app/AndroidManifest.xml
  app/build.gradle
Labels: minor (quick review), product/invisible, ready for review

#2178 Fix visibility issue of MediaController while navigation and scrolling
  app/src/org/commcare/views/media/CommCareMediaController.java
  app/src/org/commcare/views/media/MediaLayout.java
Labels: bug, product/all-users, ready for review
