Repository dimagi/commcare-android, pull requests merged in 2021-04, with the labels that each got.

#2459 Changes to support Core Api Changes for Formplayer
  app/src/org/commcare/activities/QueryRequestActivity.java
Labels: cross requested, product/invisible

#2456 Update zxing
  app/AndroidManifest.xml
  app/build.gradle
  scripts/run_danger.sh
Labels: enhancement, product/invisible

#2460 Proof of concept implementation for FileProvider Intent Media copying
  app/src/org/commcare/android/javarosa/IntentCallout.java
  app/src/org/commcare/utils/FileUtil.java
  app/unit-tests/src/org/commcare/utils/FileUtilTest.java
Labels: Release Note, bug, enhancement, product/all-users, ready for review
