Repository dimagi/commcare-android, pull requests merged in 2021-06, with the labels that each got.

#2486 Backmerge Commcare 2.51.4
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/utils/FormUploadUtil.java
Labels: product/invisible

#2489 Skip android tests if PR is trivial
  scripts/browserstack.py
Labels: product/invisible, skip-integration-tests

#2488 Fix info on package name for Support Lib
  commcare-support-library/README.md
Labels: product/invisible, skip-integration-tests

#2487 [SAAS-12293] Fix No Test Run error in BS
  scripts/browserstack.py
Labels: product/invisible

#2491 Use applicationId variable for logout permission
  app/AndroidManifest.xml
Labels: product/invisible, skip-integration-tests

#2496 Remove duplicate test class
  app/unit-tests/src/org/commcare/utils/FileUtilTest.java
Labels: minor (quick review), product/invisible, skip-integration-tests

#2494 Rotate large x axis labels on UCRs
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/utils/StringExtensionImpl.java
Labels: cross requested, enhancement, product/all-users

#2495 Fixes error handling For Session Endpoint launch
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: product/custom

#2498 PR template
  .github/pull_request_template.md
  ISSUE_TEMPLATE/bug_report.md
  ISSUE_TEMPLATE/feature_request.md
Labels: product/invisible, skip-integration-tests

#2497 [SAAS-11683] Don't save empty canvas while capturing signatures.
  app/instrumentation-tests/resources/signature_tests.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/FormAttachmentUploadTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/SignatureTests.kt
  app/res/layout/draw_layout.xml
  app/src/org/commcare/activities/DrawActivity.java
  app/src/org/commcare/views/DrawView.java
Labels: QA Note, product/all-users

#2499 Move DrawView to separate file
  app/instrumentation-tests/resources/signature_tests.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/FormAttachmentUploadTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/SignatureTests.kt
  app/res/layout/draw_layout.xml
  app/src/org/commcare/activities/DrawActivity.java
  app/src/org/commcare/views/DrawView.java
Labels: product/invisible

#2503 NPE fix in error handling for Session Endpoint
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: product/invisible

#2505 Danger android lint
  Dangerfile
Labels: product/invisible, skip-integration-tests

#2480 [SAAS-11688] Use mapbox map with capturing location
  app/AndroidManifest.xml
  app/build.gradle
  app/res/drawable/ic_current_location.xml
  app/res/layout/activity_mapbox_location_picker.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/GeoPointMapActivity.java
  app/src/org/commcare/activities/components/FormEntryDialogs.java
  app/src/org/commcare/gis/BaseMapboxActivity.kt
  app/src/org/commcare/gis/MapboxLocationPickerActivity.kt
  app/src/org/commcare/gis/MapboxLocationPickerViewModel.kt
  app/src/org/commcare/utils/GeoUtils.java
  app/src/org/commcare/views/widgets/GeoPointWidget.java
  build.gradle
Labels: QA Note, product/all-users

#2504 Changes for Formplayer merge
  app/assets/locales/android_translatable_strings.txt
  app/res/values/strings.xml
  app/src/org/commcare/activities/FormAndDataSyncer.java
  app/src/org/commcare/activities/RecoveryActivity.java
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
  app/src/org/commcare/engine/cases/CaseUtils.java
  app/src/org/commcare/models/FormRecordProcessor.java
  app/src/org/commcare/models/database/SqlStorage.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/sync/FormSubmissionHelper.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/utils/FormUploadResult.java
  app/src/org/commcare/views/dialogs/AlertDialogFragment.java
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/default/app_strings.txt
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/en/app_strings.txt
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/media_suite.xml
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/modules-0/forms-0.xml
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/modules-0/forms-1.xml
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/modules-1/forms-0.xml
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/modules-2/forms-0.xml
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/profile.ccpr
  app/unit-tests/resources/commcare-apps/cyclic_case_purge/suite.xml
  app/unit-tests/resources/inputs/case_create.xml
  app/unit-tests/resources/inputs/case_create_for_cyclic_case_purge.xml
  app/unit-tests/src/org/commcare/android/tests/formsave/CyclicCasesPurgeTest.java
  app/unit-tests/src/org/commcare/android/tests/formsave/FormRecordProcessingTest.java
  app/unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java
  app/unit-tests/src/org/commcare/android/util/ActivityLaunchUtils.java
Labels: cross requested, product/all-users
