Repository dimagi/commcare-android, pull requests merged in 2021-02, with the labels that each got.

#2434 Hide save button when recorded sound is shown
  app/src/org/commcare/views/widgets/RecordingFragment.java
Labels: minor (quick review), product/all-users

#2436 Improve attachment oversize warning message
  app/res/values/strings.xml
  app/src/org/commcare/views/widgets/QuestionWidget.java
Labels: minor (quick review), product/all-users

#2435 skip invalid case search prompts
  app/src/org/commcare/activities/QueryRequestActivity.java
  app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
  app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
Labels: product/invisible, ready for review

#2437 Use sdfat format for SD card availability check
  app/src/org/commcare/utils/FileUtil.java
Labels: bug, product/invisible

#2439 Fix hint text visibility
  app/src/org/commcare/views/QuestionsView.java
Labels: critical-bug-fix, product/all-users

#2440 Backmerge Commcare 2.51
  app/AndroidManifest.xml
  app/build.gradle
  app/res/mipmap-hdpi/commcare_launcher.png
  app/res/mipmap-mdpi/commcare_launcher.png
  app/res/mipmap-xhdpi/commcare_launcher.png
  app/res/mipmap-xxhdpi/commcare_launcher.png
  app/res/mipmap-xxxhdpi/commcare_launcher.png
  app/res/values/strings.xml
  app/res/values/themes.xml
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/QueryRequestActivity.java
  app/src/org/commcare/utils/AndroidShortcuts.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/utils/ManagerShortcut.java
  app/src/org/commcare/views/QuestionsView.java
  app/src/org/commcare/views/widgets/QuestionWidget.java
  app/src/org/commcare/views/widgets/RecordingFragment.java
  app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
  app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
  commcare-support-library/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  commcare-support-library/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  commcare-support-library/src/main/res/mipmap-hdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-hdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-mdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-mdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xxhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: product/invisible
