Repository dimagi/commcare-android, pull requests merged in 2021-08, with the labels that each got.

#2519 Update bouncy castle to 1.69
  app/build.gradle
Labels: product/invisible

#2520 [SAAS-12035] Fix calendarview UI cut off
  app/src/org/commcare/views/widgets/DateTimeWidget.java
Labels: Release Note, product/all-users

#2521 Revert zxing library update
  app/AndroidManifest.xml
  app/build.gradle
Labels: product/all-users, critical-bug-fix

#2522 Make endpoint args error more user friendly
  app/res/values/strings.xml
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: cross requested, product/invisible, product/internal-or-flagged

#2523 Backmerge Commcare 2.52.1
  app/AndroidManifest.xml
  app/build.gradle
Labels: product/invisible

#2525 Fix characterLimit is undefined error
  app/assets/graphing/graph.max.js
Labels: product/custom, skip-integration-tests
