Repository dimagi/commcare-android, pull requests merged in 2021-05, with the labels that each got.

#2465 Backmerge #2460 into hotfix
  app/src/org/commcare/android/javarosa/IntentCallout.java
  app/src/org/commcare/utils/FileUtil.java
  app/unit-tests/src/org/commcare/utils/FileUtilTest.java
Labels: product/all-users

#2455 Fix npe in FormRecordListActivity onDestroy
  app/src/org/commcare/activities/FormRecordListActivity.java
Labels: bug, product/all-users

#2463 Update markwon
  app/build.gradle
  build.gradle
Labels: minor (quick review), product/invisible

#2464 [SAAS-12159] getFileName throws an exception if extension isn't found
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/android/javarosa/IntentCallout.java
  app/src/org/commcare/preferences/FilePreferenceDialogFragmentCompat.java
  app/src/org/commcare/utils/FileExtensionNotFoundException.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/views/widgets/MediaWidget.java
  app/unit-tests/src/org/commcare/utils/FileUtilTest.java
  app/unit-tests/src/org/commcare/utils/FileUtilTest.kt
Labels: bug, product/all-users

#2452 Fixes NPE in LocationController
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/android/javarosa/PollSensorController.java
  app/src/org/commcare/location/CommCareFusedLocationController.kt
  app/src/org/commcare/location/CommCareLocationController.kt
  app/src/org/commcare/location/CommCareProviderLocationController.kt
Labels: critical-bug-fix, product/all-users

#2466 Clean session before exiting from external launch
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
Labels: bug, product/all-users

#2467 Use file backed storage for reading fixture while purging case
  app/src/org/commcare/utils/CommCareUtil.java
Labels: critical-bug-fix, product/all-users

#2471 Adds receiver to logout CC user
  app/AndroidManifest.xml
  app/res/values/strings.xml
  app/src/org/commcare/provider/CommCareLogoutReceiver.java
  app/src/org/commcare/provider/ExternalApiReceiver.java
Labels: product/custom

#2472 [SAAS-12119] Fix failures in fixture upload API
  app/instrumentation-tests/src/org/commcare/androidTests/LookupTableTest.kt
  app/instrumentation-tests/src/org/commcare/utils/HQApi.java
  app/instrumentation-tests/src/org/commcare/utils/InputStreamRequestBody.kt
Labels: don't pull, minor (quick review), product/invisible

#2474 [SAAS-12118] Use different user for different test
  app/instrumentation-tests/resources/testSavedForm.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/ClearButtonTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DemoUserOfflineTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DemoUserOnlineTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DemoUserTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/DialogTests.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FixturesTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FormAttachmentUploadTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/FormEntryTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FormFilteringTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/FormSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LanguagesTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LogSubmissionTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LookupTableTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SavedFormTest.java
  app/instrumentation-tests/src/org/commcare/androidTests/SessionExpirationTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SubmissionErrorResponseTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/SyncRecoveryTest.kt
  app/instrumentation-tests/src/org/commcare/androidTests/TilesTest.kt
Labels: minor (quick review), product/invisible

#2476 [2.51.3 hotfix] Fixes navigation drawer view
  app/src/org/commcare/activities/HomeNavDrawerController.java
Labels: product/custom

#2479 Backmerge Commcare 2.51.3
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/activities/HomeNavDrawerController.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/android/javarosa/IntentCallout.java
  app/src/org/commcare/android/javarosa/PollSensorController.java
  app/src/org/commcare/location/CommCareFusedLocationController.kt
  app/src/org/commcare/location/CommCareLocationController.kt
  app/src/org/commcare/location/CommCareProviderLocationController.kt
  app/src/org/commcare/preferences/FilePreferenceDialogFragmentCompat.java
  app/src/org/commcare/utils/FileExtensionNotFoundException.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/views/widgets/MediaWidget.java
  app/unit-tests/src/org/commcare/utils/FileUtilTest.kt
Labels: minor (quick review), product/internal-or-flagged, product/invisible

#2477 Use mp3 codec for audios recorded in commcare
  app/src/org/commcare/views/widgets/RecordingFragment.java
Labels: minor (quick review), product/invisible

#2470 [SAAS-12107] Handle captive portal in app installs
  app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
  app/src/org/commcare/engine/references/JavaHttpReference.java
  app/src/org/commcare/engine/resource/ResourceInstallUtils.java
  app/src/org/commcare/tasks/ResourceEngineTask.java
Labels: cross requested, enhancement, product/all-users

#2481 Shifts Kujaku to download from maven central
  app/build.gradle
Labels: product/invisible

#2478 Use separate preference for button font size
  app/res/values/arrays.xml
  app/src/org/commcare/preferences/FormEntryPreferences.java
  app/src/org/commcare/views/widgets/AudioWidget.java
  app/src/org/commcare/views/widgets/GeoPointWidget.java
  app/src/org/commcare/views/widgets/ImageWidget.java
  app/src/org/commcare/views/widgets/IntentWidget.java
  app/src/org/commcare/views/widgets/SignatureWidget.java
  app/src/org/commcare/views/widgets/TriggerWidget.java
  app/src/org/commcare/views/widgets/VideoWidget.java
  app/src/org/commcare/views/widgets/WidgetUtils.java
Labels: product/all-users, ready for review

#2462 [SAAS-11500] Show case name for incomplete forms
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/android/database/user/models/FormRecordV5.java
  app/src/org/commcare/logic/AndroidFormController.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
  app/src/org/commcare/tasks/FormRecordLoaderTask.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: bug, cross requested, product/all-users

#2483 Support Lib Maven Central Changes
  build.gradle
  commcare-support-library/README.md
  commcare-support-library/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: product/invisible, ready for review

#2484 [SAAS-12272] Show error if selected image is not supported by commcare
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/utils/FormUploadUtil.java
Labels: critical-bug-fix, product/all-users
