Repository dimagi/commcare-android, pull requests merged in 2021-01, with the labels that each got.

#2422 Target Android 11
  app/AndroidManifest.xml
  app/build.gradle
  app/src/org/commcare/activities/DrawActivity.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/components/FormEntryInstanceState.java
  app/src/org/commcare/gis/DrawingBoundaryActivity.kt
  app/src/org/commcare/location/CommCareProviderLocationController.kt
  app/src/org/commcare/models/ODKStorage.java
  app/src/org/commcare/preferences/FormEntryPreferences.java
  app/src/org/commcare/tasks/FormLoaderTask.java
Labels: product/all-users, ready for review

#2397 Add delete user test
  app/instrumentation-tests/src/org/commcare/androidTests/DeletedUserTest.kt
  app/instrumentation-tests/src/org/commcare/utils/HQApi.java
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
Labels: cross requested, product/invisible, ready for review

#2407 Support for CommCare Identity Hooks
  app/build.gradle
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/android/javarosa/IntentCallout.java
  app/src/org/commcare/provider/IdentityCalloutHandler.java
  app/src/org/commcare/provider/SimprintsCalloutProcessing.java
  app/src/org/commcare/views/widgets/IntentWidget.java
  app/unit-tests/resources/commcare-apps/identity_callouts/default/app_strings.txt
  app/unit-tests/resources/commcare-apps/identity_callouts/en/app_strings.txt
  app/unit-tests/resources/commcare-apps/identity_callouts/media_suite.xml
  app/unit-tests/resources/commcare-apps/identity_callouts/modules-0/forms-0.xml
  app/unit-tests/resources/commcare-apps/identity_callouts/profile.ccpr
  app/unit-tests/resources/commcare-apps/identity_callouts/suite.xml
  app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java
  app/unit-tests/src/org/commcare/android/tests/caselist/EntityListCacheIndexTest.java
  app/unit-tests/src/org/commcare/android/tests/caselist/EntityListCalloutDataTest.java
  app/unit-tests/src/org/commcare/android/tests/formentry/FormIntentTests.java
  app/unit-tests/src/org/commcare/android/tests/formentry/FormWidgetTests.java
  app/unit-tests/src/org/commcare/android/tests/formentry/IdentityCalloutTests.kt
  app/unit-tests/src/org/commcare/android/tests/formentry/IntentCalloutTests.java
  app/unit-tests/src/org/commcare/android/tests/formnav/CalendarLocaleTest.java
  app/unit-tests/src/org/commcare/android/util/ActivityLaunchUtils.java
  app/unit-tests/src/org/commcare/android/util/CaseLoadUtils.java
  app/unit-tests/src/org/commcare/android/util/TestUtils.java
  build.gradle
  commcare-support-library/build.gradle
  commcare-support-library/src/main/AndroidManifest.xml
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/CaseUtils.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/Constants.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/FixtureUtils.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/SessionStringBuilder.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/identity/IdentityResponseBuilder.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/identity/identity_integration.md
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/identity/model/IdentificationMatch.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/identity/model/MatchResult.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/identity/model/MatchStrength.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/identity/model/RegistrationResult.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/identity/model/VerificationMatch.java
  commcare-support-library/src/main/res/drawable-v24/ic_launcher_foreground.xml
  commcare-support-library/src/main/res/drawable/ic_launcher_background.xml
  commcare-support-library/src/main/res/layout/activity_main.xml
  commcare-support-library/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  commcare-support-library/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  commcare-support-library/src/main/res/mipmap-hdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-hdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-mdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-mdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xxhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/values/colors.xml
  commcare-support-library/src/main/res/values/strings.xml
  commcare-support-library/src/main/res/values/styles.xml
  settings.gradle
Labels: product/all-users

#2423 Move hearbeat to use android worker
  app/src/org/commcare/heartbeat/HeartbeatLifecycleManager.java
  app/src/org/commcare/heartbeat/HeartbeatWorker.kt
  app/src/org/commcare/services/CommCareSessionService.java
  app/unit-tests/src/org/commcare/android/tests/HeartbeatAndPromptedUpdateTests.java
Labels: product/all-users

#2429 Fix test failure caused when adding attachments
  app/instrumentation-tests/resources/ic_launcher.png
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
Labels: product/invisible

#2425 Allow strings as intent callout response.
  app/src/org/commcare/android/javarosa/IntentCallout.java
  app/unit-tests/resources/commcare-apps/phone_call/default/app_strings.txt
  app/unit-tests/resources/commcare-apps/phone_call/modules-0/forms-4.xml
  app/unit-tests/resources/commcare-apps/phone_call/suite.xml
  app/unit-tests/src/org/commcare/android/tests/formentry/IntentCalloutTests.java
Labels: product/all-users, ready for review

#2427 Move registering/unregistering of location listener to onStart/onStop
  app/src/org/commcare/activities/EntitySelectActivity.java
Labels: bug, product/all-users

#2430 Fix linking to external files
  app/res/xml/provider_paths.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/utils/MarkupUtil.java
Labels: bug, product/all-users

#2363 Add login tests
  app/instrumentation-tests/src/org/commcare/androidTests/LoginTest.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
Labels: product/invisible, ready for review

#2428 Scoped storage changes
  app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
  app/res/layout/file_pref_dialog.xml
  app/src/org/commcare/activities/InstallArchiveActivity.java
  app/src/org/commcare/activities/MultimediaInflaterActivity.java
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/fragments/CommCarePreferenceFragment.java
  app/src/org/commcare/preferences/FilePreferenceDialogFragmentCompat.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresActivity.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresPresenter.java
  app/src/org/commcare/recovery/measures/ScanCczTask.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/views/widgets/MediaWidget.java
Labels: product/all-users

#2431 Discard image when file limit exceeds.
  app/assets/locales/android_translatable_strings.txt
  app/res/values/strings.xml
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
  app/src/org/commcare/preferences/FilePreferenceDialogFragmentCompat.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/views/widgets/MediaWidget.java
Labels: bug, product/all-users

#2432 Fix crash in print activity
  app/res/values/themes.xml
Labels: bug, product/all-users

#2433 Launcher icon fix
  app/AndroidManifest.xml
  app/build.gradle
  app/res/mipmap-hdpi/commcare_launcher.png
  app/res/mipmap-mdpi/commcare_launcher.png
  app/res/mipmap-xhdpi/commcare_launcher.png
  app/res/mipmap-xxhdpi/commcare_launcher.png
  app/res/mipmap-xxxhdpi/commcare_launcher.png
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/utils/AndroidShortcuts.java
  app/src/org/commcare/utils/ManagerShortcut.java
  commcare-support-library/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  commcare-support-library/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  commcare-support-library/src/main/res/mipmap-hdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-hdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-mdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-mdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xxhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  commcare-support-library/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  commcare-support-library/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: bug, product/invisible
