Repository dimagi/commcare-android, pull requests merged in 2021-07, with the labels that each got.

#2509 bugfix: Latest CC version getting set incorrectly
  app/src/org/commcare/heartbeat/HeartbeatRequester.java
  app/unit-tests/src/org/commcare/android/tests/HeartbeatAndPromptedUpdateTests.java
Labels: product/invisible

#2510 Ensure button styles doesn't break with custom colors
  app/res/layout/list_gregorian_widget.xml
  app/res/layout/recording_fragment.xml
  app/res/layout/universal_date_widget.xml
Labels: product/all-users

#2512 Log json response for BS apis
  scripts/browserstack.py
Labels: product/invisible

#2511 Fixes case db migration
  app/src/org/commcare/android/database/user/models/ACasePreV28Model.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
  scripts/browserstack.py
Labels: product/invisible

#2513 Map fix
  app/src/org/commcare/gis/MapboxLocationPickerActivity.kt
Labels: product/all-users

#2514 Fix db update crash for FormRecord
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
Labels: critical-bug-fix, product/all-users

#2508 Adds daterange picker for case search
  app/build.gradle
  app/res/drawable-anydpi/ic_create.xml
  app/res/layout/query_prompt_layout.xml
  app/res/values/themes.xml
  app/src/org/commcare/activities/QueryRequestActivity.java
  app/src/org/commcare/utils/DateRangeUtils.java
  app/unit-tests/resources/commcare-apps/case_search_and_claim/default/app_strings.txt
  app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
  app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
  app/unit-tests/src/org/commcare/utils/DateRangeUtilsTest.java
Labels: QA Note, product/custom

#2502 Encryption support for NFC Payload
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/android/nfc/NfcActivity.java
  app/src/org/commcare/android/nfc/NfcManager.java
  app/src/org/commcare/android/nfc/NfcReadActivity.java
  app/src/org/commcare/android/nfc/NfcWriteActivity.java
  app/unit-tests/src/org/commcare/android/nfc/NfcManagerTest.java
Labels: QA Note, cross requested, product/custom

#2516 Graph js fix
  app/assets/graphing/graph.max.js
  app/assets/graphing/graph.min.js
Labels: product/all-users

#2517 Nfc delimiter Fix
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/android/nfc/NfcManager.java
  app/src/org/commcare/android/nfc/NfcWriteActivity.java
Labels: product/invisible

#2500 Add leak canary to debug builds
  app/build.gradle
Labels: product/invisible, skip-integration-tests
