Repository dimagi/commcare-android, pull requests merged in 2021-03, with the labels that each got.

#2441 Search view fix
  app/AndroidManifest.xml
  app/src/org/commcare/activities/EntitySelectSearchUI.java
Labels: bug, product/all-users

#2442 Store attachment name rather than path in formdef
  app/src/org/commcare/android/javarosa/IntentCallout.java
Labels: bug, product/invisible

#2443 Fix Memory leaks
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/GeoPointActivity.java
  app/src/org/commcare/android/javarosa/PollSensorController.java
  app/src/org/commcare/location/CommCareFusedLocationController.kt
  app/src/org/commcare/location/CommCareLocationController.kt
  app/src/org/commcare/location/CommCareProviderLocationController.kt
  app/src/org/commcare/tts/TextToSpeechConverter.kt
  app/src/org/commcare/utils/TimeoutTimer.java
Labels: bug, product/all-users

#2444 Remove bold styling from list with radio selection
  app/src/org/commcare/views/widgets/LabelWidget.java
  app/src/org/commcare/views/widgets/ListMultiWidget.java
  app/src/org/commcare/views/widgets/ListWidget.java
Labels: minor (quick review), product/all-users

#2446 Bug fix: Case query Button slides off screen
  app/res/layout/http_request_layout.xml
Labels: product/custom, ready for review

#2447 Bug fix: default values are not visibile for free text case prompts
  app/src/org/commcare/activities/QueryRequestActivity.java
  app/unit-tests/src/org/commcare/android/tests/activities/PostRequestActivityTest.java
Labels: cross requested, product/custom, ready for review

#2448 Handle receiver register/unregister calls in onResume and onPause only
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/SessionAwareCommCareActivity.java
  app/src/org/commcare/activities/SessionAwareHelper.java
  app/src/org/commcare/activities/SessionAwareListActivity.java
  app/src/org/commcare/activities/SessionAwarePreferenceActivity.java
  app/src/org/commcare/utils/CommCareExceptionHandler.java
  app/src/org/commcare/utils/SessionRegistrationHelper.java
Labels: critical-bug-fix, product/invisible

#2449 Add logs to DrawActivity
  app/src/org/commcare/activities/DrawActivity.java
  app/src/org/commcare/activities/FormEntryActivity.java
Labels: minor (quick review), product/invisible

#2454 Use bouncycastle jdk15to18 1.68
  app/build.gradle
Labels: enhancement, product/all-users

#2457 [SAAS-12009] Add Danger
  Dangerfile
  scripts/run_danger.sh
Labels: minor (quick review), product/invisible
