Repository dimagi/commcare-android, pull requests merged in 2022-07, with the labels that each got.

#2560 added test for Report Problem and added new functions in the InstrumentationUtility.kt
  app/instrumentation-tests/resources/conditional_enum_in_case_list.ccz
  app/instrumentation-tests/src/org/commcare/androidTests/ConditionalEnumInCaseListTests.kt
  app/instrumentation-tests/src/org/commcare/androidTests/LogSubmissionTest.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
  app/proguard.cfg
Labels: product/invisible

#2567 added one missing month in the listOfEthiopianMonths and also updated the format of long date format from EE, MMM dd, yyyy to EE, MMM d, yyyy
  app/instrumentation-tests/src/org/commcare/androidTests/DateWidgetsTests.kt
Labels: product/invisible

#2570 Enable Dependabot Version updates
  .github/dependabot.yml
Labels: product/invisible, dependencies

#2566 Target android 12
  README.md
  app/AndroidManifest.xml
  app/CommcareAndroidManifest.xml
  app/build.gradle
  app/src/org/commcare/CommCareNoficationManager.java
  app/src/org/commcare/android/nfc/NfcActivity.java
  app/src/org/commcare/services/CommCareSessionService.java
Labels: Release Note, product/all-users
