Repository dimagi/commcare-android, pull requests merged in 2022-08, with the labels that each got.

#2569 Android dependencies
  app/AndroidManifest.xml
  app/assets/locales/android_translatable_strings.txt
  app/instrumentation-tests/resources/android_dependency_test.ccz
  app/instrumentation-tests/src/org/commcare/AndroidPackageUtilsMock.kt
  app/instrumentation-tests/src/org/commcare/CommCareInstrumentationTestApplication.java
  app/instrumentation-tests/src/org/commcare/androidTests/ApkDependenciesTest.kt
  app/instrumentation-tests/src/org/commcare/utils/HQApi.java
  app/res/values/strings.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/StandardHomeActivity.java
  app/src/org/commcare/utils/AndroidPackageUtils.kt
  app/src/org/commcare/utils/ApkDependenciesUtils.kt
  app/src/org/commcare/utils/PlaystoreUtils.kt
  app/src/org/commcare/views/dialogs/StandardAlertDialog.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: cross requested, product/custom

#2576 [SAAS - 13808] Improve Clear User Data notification
  app/assets/locales/android_translatable_strings.txt
  app/res/values/strings.xml
  app/src/org/commcare/preferences/AdvancedActionsPreferences.java
  app/src/org/commcare/utils/StorageUtils.java
Labels: product/all-users

#2577 Fix mutability flag
  app/src/org/commcare/CommCareNoficationManager.java
  app/src/org/commcare/views/dialogs/PinnedNotificationWithProgress.java
Labels: product/invisible
