Repository dimagi/commcare-android, pull requests merged in 2023-10, with the labels that each got.

#2680 Referral Notifications - Background Sync
  app/assets/locales/android_translatable_strings.txt
  app/res/layout/custom_alert_dialog.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/CommcareListActivity.java
  app/src/org/commcare/activities/DispatchActivity.java
  app/src/org/commcare/activities/EntityDetailActivity.java
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/activities/FormAndDataSyncer.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/HomeButtons.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/MenuActivity.java
  app/src/org/commcare/gis/EntityMapActivity.java
  app/src/org/commcare/interfaces/CommcareRequestEndpoints.java
  app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
  app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
  app/src/org/commcare/models/AndroidSessionWrapper.java
  app/src/org/commcare/network/CommcareRequestEndpointsMock.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
  app/src/org/commcare/network/DataPullRequester.java
  app/src/org/commcare/network/DataPullResponseFactory.java
  app/src/org/commcare/network/LocalReferencePullResponseFactory.java
  app/src/org/commcare/network/mocks/LocalFilePullResponseFactory.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/provider/ExternalApiReceiver.java
  app/src/org/commcare/services/CommCareFirebaseMessagingService.java
  app/src/org/commcare/services/DataSyncCompleteBroadcastReceiver.java
  app/src/org/commcare/services/FCMMessageData.java
  app/src/org/commcare/services/PendingSyncAlertBroadcastReceiver.java
  app/src/org/commcare/sync/ExternalDataUpdateHelper.java
  app/src/org/commcare/sync/FirebaseMessagingDataSyncer.java
  app/src/org/commcare/sync/FormSubmissionWorker.kt
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/utils/FirebaseMessagingUtil.java
  app/src/org/commcare/utils/Permissions.java
  app/src/org/commcare/views/dialogs/PinnedNotificationWithProgress.java
  app/src/org/commcare/views/dialogs/StandardAlertDialog.java
  app/unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: Release Note, QA Note, High Risk

#2719 Connect App verification
  app/src/org/commcare/activities/CommCareVerificationActivity.java
  app/src/org/commcare/activities/connect/ConnectActivity.java
  app/src/org/commcare/fragments/connect/ConnectDownloadingFragment.java
Labels: product/invisible

#2720 Enable back button on connect activity
  app/src/org/commcare/activities/DispatchActivity.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/connect/ConnectActivity.java
Labels: skip-integration-tests

#2681 Enable Certificate Transparency with OkHTTP Update
  app/AndroidManifest.xml
  app/build.gradle
  app/proguard.cfg
  app/res/xml/preferences_developer.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/network/CTInterceptorConfig.kt
  app/src/org/commcare/network/ISRGCertConfig.java
  app/src/org/commcare/network/OkHttpBuilderCustomConfig.java
  app/src/org/commcare/preferences/DeveloperPreferences.java
  app/src/org/commcare/preferences/HiddenPreferences.java
Labels: Release Note, QA Note

#2717 Move Firebase Database URL to Android secrets
  app/build.gradle
  app/templates/google-services.json
Labels: product/invisible

#2726 Adds model class in test
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: cross requested
