Repository dimagi/commcare-android, pull requests merged in 2024-09, with the labels that each got.

#2840 Google map SDK version upgrade from 17.0.0 to 19.0.0
  app/build.gradle
Labels: QA Note

#2850 Fixes a bug causing Updates to get stale
  app/src/org/commcare/heartbeat/HeartbeatWorker.kt
  app/src/org/commcare/update/UpdateHelper.java
  app/src/org/commcare/update/UpdateWorker.kt
  app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.kt
  app/unit-tests/src/org/commcare/update/UpdateWorkerTest.kt
Labels: cross requested

#2853 Add end to end dev guide to README
  README.md
Labels: product/invisible, skip-integration-tests

#2843 Added support for translations to fetch from server for repeat group …
  app/assets/locales/android_translatable_strings.txt
  app/instrumentation-tests/src/org/commcare/androidTests/DialogTests.kt
  app/src/org/commcare/activities/FormEntryActivityUIController.java
Labels: Release Note, skip-integration-tests, QA Note
