Repository dimagi/commcare-android, pull requests merged in 2024-10, with the labels that each got.

#2852 Change log server URL locally
  app/res/xml/preferences_developer.xml
  app/src/org/commcare/preferences/DeveloperPreferences.java
Labels: QA Note

#2848 Fix an issue when unregistering Pending Sync Alerts receiver
  app/src/org/commcare/activities/FormEntryActivity.java
Labels: product/invisible

#2867 Fixes form navigation error due to multiple search callout extras
  app/src/org/commcare/adapters/EntityListAdapter.java
Labels: skip-integration-tests

#2805 Feature/givewell
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/res/xml/main_preferences.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/CommCareNoficationManager.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/interfaces/FormSaveCallback.java
  app/src/org/commcare/interfaces/FormSavedListener.java
  app/src/org/commcare/logic/AndroidFormController.java
  app/src/org/commcare/models/AndroidSessionWrapper.java
  app/src/org/commcare/models/database/InterruptedFormState.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/preferences/MainConfigurablePreferences.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/sync/ExternalDataUpdateHelper.java
  app/src/org/commcare/sync/FirebaseMessagingDataSyncer.java
  app/src/org/commcare/tasks/FormLoaderTask.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
  app/src/org/commcare/utils/SerializationUtil.java
  app/src/org/commcare/utils/StringUtils.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: cross requested

#2885 Remove microphone status check for Android 9 and lower
  app/src/org/commcare/views/widgets/RecordingFragment.java
Labels: product/invisible

#2886 Include original exception in wrapper InvalidStateException
  app/src/org/commcare/android/database/user/models/FormRecord.java
Labels: product/invisible
