Repository dimagi/commcare-android, pull requests merged in 2024-04, with the labels that each got.

#2738 Connect QA Branch
  app/assets/locales/android_translatable_strings.txt
  app/res/layout/connect_payment_item.xml
  app/res/layout/fragment_connect_delivery_progress.xml
  app/res/layout/fragment_connect_progress_delivery.xml
  app/res/layout/screen_login.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/DispatchActivity.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/LoginActivityUiController.java
  app/src/org/commcare/activities/connect/ConnectDatabaseHelper.java
  app/src/org/commcare/activities/connect/ConnectIdRegistrationActivity.java
  app/src/org/commcare/activities/connect/ConnectManager.java
  app/src/org/commcare/activities/connect/ConnectNetworkHelper.java
  app/src/org/commcare/activities/connect/ConnectSsoHelper.java
  app/src/org/commcare/android/database/connect/models/ConnectJobPaymentRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectJobPaymentRecordV3.java
  app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecordV3.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
  app/src/org/commcare/fragments/connect/ConnectResultsListFragment.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
  app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
  commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/CommCareLauncher.java
Labels: skip-integration-tests

#2732 Moves Async entity Implementation to Core
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/adapters/EntityListAdapter.java
  app/src/org/commcare/interfaces/AndroidSortableEntityAdapter.java
  app/src/org/commcare/models/AsyncEntity.java
  app/src/org/commcare/models/AsyncNodeEntityFactory.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/models/CommCareEntityStorageCache.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/EntityLoaderTask.java
  app/src/org/commcare/utils/StringUtils.java
  app/src/org/commcare/views/EntityView.java
  app/src/org/commcare/views/EntityViewTile.java
  app/src/org/commcare/xml/AndroidBulkCaseXmlParser.java
  app/src/org/commcare/xml/AndroidCaseXmlParser.java
  app/unit-tests/src/org/commcare/android/util/TestUtils.java
Labels: cross requested, QA Note

#2744 Allow Unsynced Time Limit to be set in hours
  app/src/org/commcare/utils/SyncDetailCalculations.java
Labels: product/invisible

#2669 Gradle 8 updates
  app/build.gradle
  app/instrumentation-tests/AndroidManifest.xml
  app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
  app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt
  app/jacoco.gradle
  app/proguard.cfg
  app/test-proguard.cfg
  build.gradle
  commcare-support-library/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: cross requested, product/invisible

#2747 Add fullscreen option to in-line videos
  app/AndroidManifest.xml
  app/res/drawable-hdpi/ic_media_exit_fullscreen.png
  app/res/drawable-hdpi/ic_media_fullscreen.png
  app/res/drawable-ldpi/ic_media_exit_fullscreen.png
  app/res/drawable-ldpi/ic_media_fullscreen.png
  app/res/drawable-mdpi/ic_media_exit_fullscreen.png
  app/res/drawable-mdpi/ic_media_fullscreen.png
  app/res/drawable-xhdpi/ic_media_exit_fullscreen.png
  app/res/drawable-xhdpi/ic_media_fullscreen.png
  app/res/drawable-xxhdpi/ic_media_exit_fullscreen.png
  app/res/drawable-xxhdpi/ic_media_fullscreen.png
  app/res/layout/activity_fullscreen_video_view.xml
  app/res/values/styles.xml
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FullscreenVideoViewActivity.kt
  app/src/org/commcare/activities/components/FormEntryConstants.java
  app/src/org/commcare/views/media/CommCareMediaController.java
  app/src/org/commcare/views/media/CommCareVideoView.java
  app/src/org/commcare/views/media/MediaLayout.java
Labels: Release Note, QA Note
