Repository dimagi/commcare-android, pull requests merged in 2024-08, with the labels that each got.

#2757 Providing API version header from server to caller when available.
  app/src/org/commcare/activities/InstallFromListActivity.java
  app/src/org/commcare/activities/PostRequestActivity.java
  app/src/org/commcare/activities/QueryRequestActivity.java
  app/src/org/commcare/network/GetAndParseActor.java
  app/src/org/commcare/tasks/ModernHttpTask.java
Labels: cross requested, skip-integration-tests

#2802 Auto-Save Form on Pause
  app/res/xml/preferences_developer.xml
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/interfaces/FormSaveCallback.java
  app/src/org/commcare/interfaces/FormSavedListener.java
  app/src/org/commcare/logic/AndroidFormController.java
  app/src/org/commcare/models/AndroidSessionWrapper.java
  app/src/org/commcare/preferences/DeveloperPreferences.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
  app/src/org/commcare/utils/StringUtils.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: cross requested

#2808 Move autosave preference from developer options to user settings
  app/res/xml/main_preferences.xml
  app/res/xml/preferences_developer.xml
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/preferences/DeveloperPreferences.java
  app/src/org/commcare/preferences/MainConfigurablePreferences.java
Labels: product/all-users

#2809 Add logging when session recovery is identified
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/services/CommCareSessionService.java
Labels: product/invisible

#2798 UKRs managed by server for Connect apps
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/LoginActivityUiController.java
  app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecordV8.java
  app/src/org/commcare/connect/ConnectDatabaseHelper.java
  app/src/org/commcare/connect/ConnectManager.java
  app/src/org/commcare/connect/network/ConnectSsoHelper.java
  app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
  app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
  app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
  app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
  app/src/org/commcare/utils/CrashUtil.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: skip-integration-tests

#2824 Backmerge Commcare 2.54.0
  app/AndroidManifest.xml
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/instrumentation-tests/src/org/commcare/androidTests/InstallFromListTest.kt
  app/instrumentation-tests/src/org/commcare/utils/HQApi.java
  app/res/drawable/ic_cc_update.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/HomeButtons.java
  app/src/org/commcare/activities/HomeNavDrawerController.java
  app/src/org/commcare/activities/QueryRequestUiController.kt
  app/src/org/commcare/android/database/global/models/ConnectKeyRecord.java
  app/src/org/commcare/android/database/global/models/ConnectKeyRecordV6.java
  app/src/org/commcare/engine/resource/AndroidResourceManager.java
  app/src/org/commcare/engine/resource/ResourceInstallUtils.java
  app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
  app/src/org/commcare/models/database/global/GlobalDatabaseUpgrader.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/tasks/ResourceEngineTask.java
  app/src/org/commcare/update/UpdateWorker.kt
  app/src/org/commcare/utils/AndroidXUtils.java
  app/src/org/commcare/utils/DateRangeUtils.java
  app/src/org/commcare/views/widgets/CommCareAudioWidget.java
  app/src/org/commcare/views/widgets/MediaWidget.java
  app/src/org/commcare/views/widgets/RecordingFragment.java
  app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
  app/unit-tests/src/org/commcare/utils/DateRangeUtilsTest.java
  build.gradle
Labels: product/invisible

#2826 Fixes AS make project Function
  app/build.gradle
Labels: skip-integration-tests
