Repository dimagi/commcare-android, pull requests merged in 2024-12, with the labels that each got.

#2903 Remove misleading comment reg. 1 MB Sql Limitation
  app/src/org/commcare/models/database/user/models/CommCareEntityStorageCache.java
Labels: skip-integration-tests

#2906 logs exceptions encountered while saving image
  app/src/org/commcare/activities/components/ImageCaptureProcessing.java
Labels: skip-integration-tests

#2908 Lint only changed files in the PR
  .github/workflows/linter.yml
Labels: skip-integration-tests

#2911 Removes some logs which are killing our sumo usage
  app/src/org/commcare/activities/CommCareGraphActivity.java
  app/src/org/commcare/android/javarosa/IntentCallout.java
  app/src/org/commcare/appupdate/CommcareFlexibleAppUpdateManager.java
  app/src/org/commcare/graph/view/GraphView.java
  app/src/org/commcare/preferences/HiddenPreferences.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/LogSubmissionTask.java
  app/src/org/commcare/utils/FormUploadUtil.java
Labels: skip-integration-tests

#2910 enable gradle configuration cache
  gradle.properties
Labels: skip-integration-tests

#2865 Remove unused cipher pool
  app/src/org/commcare/models/encryption/CipherPool.java
  app/src/org/commcare/models/legacy/DecryptingCursor.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
Labels: skip-integration-tests

#2894 Android 14 update
  app/AndroidManifest.xml
  app/build.gradle
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/CommCareWiFiDirectActivity.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/location/CommCareProviderLocationController.kt
  app/src/org/commcare/services/CommCareFirebaseMessagingService.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/utils/SessionRegistrationHelper.java
  build.gradle
  commcare-support-library/build.gradle
  commcare-support-library/src/main/AndroidManifest.xml
Labels: Release Note, QA Note, High Risk

#2914 Report all non fatals to firebase
  app/src/org/commcare/logging/AndroidLogger.java
  app/src/org/commcare/logging/PreInitLogger.java
  app/src/org/commcare/tasks/templates/CommCareTask.java
Labels: cross requested

#2918 Fix Mapbox SDK dependency issue
  app/build.gradle
Labels: product/invisible

#2873 Migrate to ViewPager2
  app/AndroidManifest.xml
  app/build.gradle
  app/libs/rtl-viewpager-2.0.0.aar
  app/res/drawable/title_case_tab_vertical.xml
  app/res/drawable/title_neutral_tab_vertical.xml
  app/res/layout/tabbed_detail_view.xml
  app/res/values/dimens.xml
  app/res/values/styles.xml
  app/src/org/commcare/activities/EntityDetailActivity.java
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/adapters/EntityDetailPagerAdapter.java
  app/src/org/commcare/fragments/BreadcrumbBarFragment.java
  app/src/org/commcare/views/TabbedDetailView.java
Labels: QA Note
