Repository dimagi/commcare-android, pull requests merged in 2025-05, with the labels that each got.

#3064 Pm-fixed bug for job status button click and landing page for connect
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/connect/ConnectIdActivity.java
  app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
  app/src/org/commcare/connect/ConnectConstants.java
Labels: cross requested, skip-integration-tests

#3063 Connect Lint clean up on Common Files + bring files up to date with master
  app/AndroidManifest.xml
  app/src/org/commcare/activities/AppManagerActivity.java
  app/src/org/commcare/activities/AppSelectActivity.java
  app/src/org/commcare/activities/AppSelectActivityUiController.java
  app/src/org/commcare/adapters/AppSelectAdapter.java
  app/src/org/commcare/heartbeat/HeartbeatWorker.kt
  app/src/org/commcare/models/database/user/models/CommCareEntityStorageCache.java
  app/src/org/commcare/preferences/MainConfigurablePreferences.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/tasks/ModernHttpTask.java
  app/src/org/commcare/tasks/SaveToDiskTask.java
  app/src/org/commcare/update/UpdateHelper.java
  app/src/org/commcare/update/UpdateWorker.kt
  app/src/org/commcare/utils/CommCareLifecycleUtils.java
  app/src/org/commcare/utils/CrashUtil.java
  app/src/org/commcare/utils/EnhancedWrapContentViewPager.java
  app/src/org/commcare/utils/KeyboardHelper.java
  app/src/org/commcare/utils/MediaUtil.java
  app/src/org/commcare/utils/SerializationUtil.java
  app/src/org/commcare/views/media/CommCareMediaController.java
  app/src/org/commcare/views/widgets/RecordingFragment.java
  app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.kt
Labels: skip-integration-tests

#3065 Reviewed: Messaging section
  app/res/values/strings.xml
  app/src/org/commcare/activities/connect/ConnectActivity.java
  app/src/org/commcare/activities/connect/ConnectMessagingActivity.java
  app/src/org/commcare/connect/MessageManager.java
  app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelConsentBottomSheet.java
  app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelListFragment.java
Labels: skip-integration-tests

#3043 Several updates to Connect DB (versions 11, 12, and 13).
  app/src/org/commcare/android/database/connect/models/ConnectJobDeliveryFlagRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectJobDeliveryRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectJobRecordV10.java
  app/src/org/commcare/android/database/connect/models/ConnectMessagingChannelRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectMessagingMessageRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectPaymentUnitRecord.java
  app/src/org/commcare/connect/database/ConnectDatabaseUtils.java
  app/src/org/commcare/connect/database/ConnectJobUtils.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
  app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
  app/src/org/commcare/utils/EncryptionUtils.java
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
  app/unit-tests/src/org/commcare/utils/EncryptionUtilsTest.java
Labels: cross requested

#3040 Show flags for deliveries
  app/src/org/commcare/android/database/connect/models/ConnectJobDeliveryFlagRecord.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryListFragment.java
Labels: cross requested, skip-integration-tests

#3071 make biometric available for api version less than 28
  app/res/navigation/nav_graph_connectid.xml
  app/src/org/commcare/fragments/connectId/ConnectIdMessageFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdPinFragment.java
  app/src/org/commcare/utils/BiometricsHelper.java
Labels: cross requested, skip-integration-tests

#3076 Pm-bug fixes for connect, and biometric fix
  app/res/layout/fragment_recovery_code.xml
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
  app/src/org/commcare/connect/ConnectIDManager.java
  app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
  app/src/org/commcare/utils/JsonExtensions.kt
  app/src/org/commcare/views/connect/CustomOtpView.java
Labels: cross requested, skip-integration-tests

#3075 Brings back missing analytics events And Token Exceptions Handling
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/LoginActivityUIController.java
  app/src/org/commcare/activities/NavigationHostCommCareActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/activities/connect/ConnectActivity.java
  app/src/org/commcare/activities/connect/ConnectIdActivity.java
  app/src/org/commcare/activities/connect/ConnectMessagingActivity.java
  app/src/org/commcare/connect/ConnectIDManager.java
  app/src/org/commcare/connect/MessageManager.java
  app/src/org/commcare/connect/network/ApiConnectId.java
  app/src/org/commcare/connect/network/ConnectSsoHelper.java
  app/src/org/commcare/connect/network/TokenDeniedException.kt
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
  app/src/org/commcare/network/HttpCalloutTask.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/ManageKeyRecordTask.java
  app/src/org/commcare/views/notifications/NotificationMessageFactory.java
Labels: skip-integration-tests

#3080 Remove connect enable setting
  app/res/xml/app_manager_developer_preferences.xml
  app/src/org/commcare/connect/ConnectIDManager.java
  app/src/org/commcare/preferences/AppManagerDeveloperPreferences.java
Labels: skip-integration-tests

#3073 Merge common CC files from Connect
  app/assets/locales/android_translatable_strings.txt
  app/res/drawable-anydpi/ic_marker.xml
  app/res/xml/app_manager_developer_preferences.xml
  app/src/org/commcare/activities/CommCareVerificationActivity.java
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/LoginActivityUIController.java
  app/src/org/commcare/activities/NavigationHostCommCareActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/connect/ConnectIDManager.java
  app/src/org/commcare/connect/network/ApiConnectId.java
  app/src/org/commcare/connect/network/ConnectNetworkHelper.java
  app/src/org/commcare/connect/network/ConnectSsoHelper.java
  app/src/org/commcare/connect/network/IApiCallback.java
  app/src/org/commcare/connect/network/TokenDeniedException.kt
  app/src/org/commcare/fragments/connectId/ConnectIDSecondaryPhoneNumber.java
  app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdPhoneFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdPinFragment.java
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
  app/src/org/commcare/network/HttpCalloutTask.java
  app/src/org/commcare/network/HttpUtils.java
  app/src/org/commcare/preferences/AppManagerDeveloperPreferences.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/services/FCMMessageData.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/ManageKeyRecordTask.java
  app/src/org/commcare/views/notifications/NotificationMessageFactory.java
Labels: skip-integration-tests

#3082 Correct method name
  app/src/org/commcare/connect/ConnectManager.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
  app/src/org/commcare/fragments/connect/ConnectUnlockFragment.java
Labels: skip-integration-tests

#3085 removed unused drawables not used in master and dv/connect_initial both
  app/res/drawable-hdpi/ic_action_overflow.png
  app/res/drawable-hdpi/ic_logout_action_bar.png
  app/res/drawable-hdpi/ic_trashcan.png
  app/res/drawable-ldpi/door.png
  app/res/drawable/avatar_person.png
  app/res/drawable/avatar_vellum_android_intent.png
  app/res/drawable/avatar_vellum_group.png
  app/res/drawable/avatar_vellum_hidden_value.png
  app/res/drawable/avatar_vellum_image_capture.png
  app/res/drawable/avatar_vellum_phonenumber.png
  app/res/drawable/avatar_vellum_signature.png
  app/res/drawable/avatar_vellum_time.png
  app/res/drawable/blue_outlined_view.xml
  app/res/drawable/bottom_shadow.xml
  app/res/drawable/expander_ic_right.png
  app/res/drawable/ic_connect_arrow_back.xml
  app/res/drawable/ic_maps_indicator_current_position.png
  app/res/drawable/ic_notifications_24.xml
  app/res/drawable/icon_audioplay_lightcool.png
  app/res/drawable/icon_audiostop_darkwarm.png
  app/res/drawable/icon_chevron_right_primary.png
  app/res/drawable/icon_choice_marked_attnpos.png
  app/res/drawable/icon_choice_outline_neutral.png
  app/res/drawable/radio_button_modern.xml
  app/res/drawable/record_complete.png
  app/res/drawable/tile_drop_shadow.9.png
  app/res/drawable/tile_drop_shadow_small_margins_depressed.9.png
  app/res/drawable/title_case_tab.xml
  app/res/drawable/title_neutral_tab.xml
  app/res/layout/activity_uitest_info.xml
  app/res/layout/recording.xml
  app/res/layout/screen_connect_login.xml
  commcare-support-library/src/main/res/drawable-v24/ic_launcher_foreground.xml
  commcare-support-library/src/main/res/drawable/ic_launcher_background.xml
Labels: skip-integration-tests

#3086 Use constructor for delivery details
  app/src/org/commcare/android/database/connect/models/ConnectDeliveryDetails.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java
Labels: skip-integration-tests

#3084 Pulling in latest model changes for Connect
  app/src/org/commcare/android/database/connect/models/ConnectAppRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectDeliveryDetails.java
  app/src/org/commcare/android/database/connect/models/ConnectDeliveryPaymentSummaryInfo.java
  app/src/org/commcare/android/database/connect/models/ConnectJobAssessmentRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectJobDeliveryFlagRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectJobLearningRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectJobPaymentRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectJobPaymentRecordV3.java
  app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectUserRecord.java
  app/src/org/commcare/connect/ConnectIDManager.java
Labels: skip-integration-tests

#3091 Pm-fix direction issue with password , "null" issue,
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/StandardHomeActivityUIController.java
  app/src/org/commcare/activities/connect/ConnectActivity.java
  app/src/org/commcare/activities/connect/ConnectIdActivity.java
  app/src/org/commcare/android/database/connect/models/ConnectJobDeliveryRecord.java
  app/src/org/commcare/connect/ConnectIDManager.java
  app/src/org/commcare/connect/ConnectManager.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryListFragment.java
Labels: skip-integration-tests

#3095 PM-fixing crash on click message icon
  app/res/layout/fragment_connect_delivery_progress.xml
  app/src/org/commcare/connect/ConnectManager.java
Labels: cross requested, skip-integration-tests

#3098 -fixes from regression qa fixes
  app/res/layout/fragment_connect_delivery_progress.xml
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/StandardHomeActivityUIController.java
  app/src/org/commcare/activities/connect/ConnectActivity.java
  app/src/org/commcare/activities/connect/ConnectIdActivity.java
  app/src/org/commcare/connect/ConnectIDManager.java
  app/src/org/commcare/connect/ConnectManager.java
  app/src/org/commcare/connect/database/ConnectJobUtils.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryListFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
  app/src/org/commcare/views/connect/CustomOtpView.java
Labels: cross requested, skip-integration-tests

#3069 Improve image downscaling using progressive steps to reduce artifacts.
  app/src/org/commcare/utils/FileUtil.java
Labels: 🙋 Bounty claim

#3103 -updated formStorageTest file with latest Xpath functions
  app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Labels: cross requested, Release Note, skip-integration-tests

#3111 Connect Message review
  app/AndroidManifest.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/connect/ConnectMessagingActivity.java
  app/src/org/commcare/adapters/ChannelAdapter.java
  app/src/org/commcare/connect/MessageManager.java
  app/src/org/commcare/connect/database/ConnectMessagingDatabaseHelper.java
  app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelConsentBottomSheet.java
  app/src/org/commcare/fragments/connectMessaging/ConnectMessageFragment.java
  app/src/org/commcare/services/CommCareFirebaseMessagingService.java
Labels: skip-integration-tests

#3109 UI Changes to Connect ID Device Configuration Workflow
  app/res/drawable-hdpi/commcare_connect_logo.png
  app/res/drawable-ldpi/commcare_connect_logo.png
  app/res/drawable-mdpi/commcare_connect_logo.png
  app/res/drawable-xhdpi/commcare_connect_logo.png
  app/res/drawable-xxhdpi/commcare_connect_logo.png
  app/res/drawable-xxxhdpi/commcare_connect_logo.png
  app/res/layout/activity_connect_id.xml
  app/res/layout/fragment_phone_available_bottom_sheet.xml
  app/res/layout/fragment_recovery_code.xml
  app/res/layout/fragment_secondary_phone_number.xml
  app/res/layout/screen_connect_password_verify.xml
  app/res/layout/screen_connect_primary_phone.xml
  app/res/layout/screen_connect_user_deactivate_otp_verify.xml
  app/res/layout/screen_personalid_name.xml
  app/res/layout/screen_personalid_phone_verify.xml
  app/res/layout/screen_personalid_phoneno.xml
  app/res/navigation/nav_graph_connectid.xml
  app/res/navigation/nav_graph_personalid.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/connect/ConnectIdActivity.java
  app/src/org/commcare/connect/network/ApiConnectId.java
  app/src/org/commcare/fragments/connectId/ConnectIDSecondaryPhoneNumber.java
  app/src/org/commcare/fragments/connectId/ConnectIdPhoneAvailableBottomSheet.java
  app/src/org/commcare/fragments/connectId/ConnectIdPhoneFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdUserDeactivateOTPVerificationFragment.java
  app/src/org/commcare/fragments/connectId/PersonalIdBackupCodeFragment.java
  app/src/org/commcare/fragments/connectId/PersonalIdBiometricConfigFragment.java
  app/src/org/commcare/fragments/connectId/PersonalIdMessageFragment.java
  app/src/org/commcare/fragments/connectId/PersonalIdNameFragment.java
  app/src/org/commcare/fragments/connectId/PersonalIdPasswordVerificationFragment.java
  app/src/org/commcare/fragments/connectId/PersonalIdPhoneFragment.java
  app/src/org/commcare/fragments/connectId/PersonalIdPhoneVerificationFragment.java
Labels: skip-integration-tests, High Risk

#3115 - removed duplicate dependencies
  app/build.gradle
Labels: skip-integration-tests

#3116 Implement Personal ID face capture Page
  app/AndroidManifest.xml
  app/assets/locales/android_translatable_strings.txt
  app/build.gradle
  app/res/drawable/baseline_person_24.xml
  app/res/drawable/ic_camera_shutter.xml
  app/res/layout/micro_image_widget.xml
  app/res/layout/screen_personalid_photo_capture.xml
  app/res/navigation/nav_graph_personalid.xml
  app/res/values/attrs.xml
  app/res/values/colors.xml
  app/res/values/strings.xml
  app/src/org/commcare/android/database/connect/models/ConnectUserRecord.java
  app/src/org/commcare/connect/network/ApiPersonalId.java
  app/src/org/commcare/connect/network/connectId/ApiEndPoints.java
  app/src/org/commcare/connect/network/connectId/ApiService.java
  app/src/org/commcare/fragments/MicroImageActivity.java
  app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
  app/src/org/commcare/fragments/personalId/PersonalIdPhotoCaptureFragment.java
  app/src/org/commcare/utils/AndroidUtil.java
  app/src/org/commcare/utils/FileUtil.java
  app/src/org/commcare/utils/ImageSizeTooLargeException.java
  app/src/org/commcare/utils/MediaUtil.java
  app/src/org/commcare/views/FaceCaptureView.java
  build.gradle
Labels: skip-integration-tests

#3120 Added the french localisation as per the sheet
  app/res/values-fr/strings.xml
Labels: skip-integration-tests

#3119 -ui design for to show photo in backup page at time of recovery
  app/res/layout/fragment_recovery_code.xml
  app/res/values/strings.xml
  app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
Labels: skip-integration-tests

#3123 call api for check_name
  app/src/org/commcare/connect/network/ApiPersonalId.java
  app/src/org/commcare/connect/network/PersonalIdApiErrorHandler.java
  app/src/org/commcare/connect/network/PersonalIdApiHandler.java
  app/src/org/commcare/connect/network/connectId/ApiEndPoints.java
  app/src/org/commcare/connect/network/connectId/ApiService.java
  app/src/org/commcare/connect/network/parser/AddOrVerifyNameParser.java
  app/src/org/commcare/connect/network/parser/PersonalIdApiResponseParser.java
  app/src/org/commcare/connect/network/parser/StartConfigurationResponseParser.java
  app/src/org/commcare/fragments/personalId/PersonalIdNameFragment.java
  app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
Labels: skip-integration-tests

#3131 Fixes a crash on Connect ID signup due to incorrect View Model constructor
  app/src/org/commcare/android/integrity/IntegrityTokenViewModel.kt
Labels: skip-integration-tests

#3124 - Restricted demo user from sending firebase otp
  app/res/navigation/nav_graph_personalid.xml
  app/res/values-pt/strings.xml
  app/res/values-sw/strings.xml
  app/res/values-ti/strings.xml
  app/res/values/strings.xml
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/fragments/personalId/PersonalIdBiometricConfigFragment.java
  app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
  app/src/org/commcare/utils/ViewUtils.java
Labels: skip-integration-tests

#3132 Adds info on Google Cloud Project
  README.md
Labels: skip-integration-tests

#3113 - Added firebase otp send and receive helper class
  app/build.gradle
  app/src/org/commcare/utils/FirebaseAuthService.java
  app/src/org/commcare/utils/OtpAuthService.java
  app/src/org/commcare/utils/OtpManager.java
  app/src/org/commcare/utils/OtpVerificationCallback.java
Labels: skip-integration-tests

#3133 Confirm backup code api call
  app/src/org/commcare/connect/network/ApiPersonalId.java
  app/src/org/commcare/connect/network/PersonalIdApiHandler.java
  app/src/org/commcare/connect/network/connectId/ApiEndPoints.java
  app/src/org/commcare/connect/network/connectId/ApiService.java
  app/src/org/commcare/connect/network/parser/ConfirmBackupCodeResponseParser.java
  app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
  app/src/org/commcare/fragments/personalId/PersonalIdPhotoCaptureFragment.java
  app/src/org/commcare/utils/MediaUtil.java
Labels: skip-integration-tests

#3136 request hash for integrity token needs padding
  app/src/org/commcare/utils/HashUtils.kt
Labels: skip-integration-tests

#3138 Integrity token issue solved
  app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
Labels: skip-integration-tests

#3126 -put extra check for getHq token
  app/src/org/commcare/connect/PersonalIdManager.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
Labels: skip-integration-tests

#3140 Adding app meta data as per https://dimagi.atlassian.net/browse/CCCT-1296
  app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
Labels: skip-integration-tests

#3139 Complete profile refactor
  app/src/org/commcare/connect/network/ApiPersonalId.java
  app/src/org/commcare/connect/network/PersonalIdApiHandler.java
  app/src/org/commcare/connect/network/parser/CompleteProfileResponseParser.java
  app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
  app/src/org/commcare/fragments/personalId/PersonalIdNameFragment.java
  app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
  app/src/org/commcare/fragments/personalId/PersonalIdPhotoCaptureFragment.java
Labels: skip-integration-tests
