Repository dimagi/commcare-android, pull requests merged in 2025-10, with the labels that each got.

#3350 Commcare 2.59 backmerge
  app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
Labels: cross requested, skip-integration-tests

#3354 Cleaned up local DB passphrase code
  app/res/values/strings.xml
  app/src/org/commcare/android/database/global/models/ConnectKeyRecord.java
  app/src/org/commcare/connect/PersonalIdManager.java
  app/src/org/commcare/connect/database/ConnectDatabaseHelper.java
  app/src/org/commcare/connect/database/ConnectDatabaseUtils.java
  app/src/org/commcare/connect/network/ApiPersonalId.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
Labels: skip-integration-tests, QA Note

#3355 Improved logging on fcm token nullability
  app/src/org/commcare/utils/FirebaseMessagingUtil.java
Labels: skip-integration-tests

#3356 Locking ConnectActivity to portrait screen orientation
  app/AndroidManifest.xml
Labels: Release Note, QA Note

#3359 Fixes crash on clicking View Job Status
  app/src/org/commcare/activities/connect/ConnectActivity.java
Labels: skip-integration-tests
