Repository dimagi/commcare-android, pull requests merged in 2025-03, with the labels that each got.

#2928 Cache and Lazy-Load Modifications
  app/build.gradle
  app/res/layout/entity_select_layout.xml
  app/res/values/strings.xml
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/engine/cases/CaseUtils.java
  app/src/org/commcare/entity/AndroidAsyncNodeEntityFactory.kt
  app/src/org/commcare/fragments/EntitySubnodeDetailFragment.java
  app/src/org/commcare/heartbeat/HeartbeatRequester.java
  app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
  app/src/org/commcare/models/database/SqlStorage.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/models/CommCareEntityStorageCache.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/EntityCacheInvalidationWorker.kt
  app/src/org/commcare/tasks/EntityLoaderHelper.kt
  app/src/org/commcare/tasks/EntityLoaderListener.java
  app/src/org/commcare/tasks/EntityLoaderTask.java
  app/src/org/commcare/tasks/PrimeEntityCache.kt
  app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
  app/src/org/commcare/update/UpdateHelper.java
  app/src/org/commcare/xml/AndroidBulkCaseXmlParser.java
  app/src/org/commcare/xml/AndroidCaseXmlParser.java
  app/unit-tests/resources/commcare-apps/case_list_lookup/restore.xml
  app/unit-tests/resources/commcare-apps/index_and_cache_test/incremental_restore.xml
  app/unit-tests/resources/commcare-apps/index_and_cache_test/suite.xml
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
  app/unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java
  app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/PostRequestActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/activities/UpdateActivityTest.java
  app/unit-tests/src/org/commcare/android/tests/caselist/EntityListCacheIndexTest.java
  app/unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java
Labels: cross requested, QA Note

#2963 Remove media permissions
  app/AndroidManifest.xml
  app/instrumentation-tests/src/org/commcare/androidTests/BaseTest.kt
  app/src/org/commcare/utils/Permissions.java
  app/src/org/commcare/views/widgets/ImageWidget.java
  app/src/org/commcare/views/widgets/VideoWidget.java
  app/src/org/commcare/views/widgets/WidgetUtils.java
Labels: QA Note

#2969 Address minor UI feedback
  app/res/drawable-ldpi/ic_blue_backward.png
  app/res/drawable-ldpi/ic_blue_forward.png
  app/res/drawable-ldpi/icon_chevron_left_brand.png
  app/res/drawable-ldpi/icon_chevron_right_brand.png
  app/res/drawable-mdpi/ic_blue_backward.png
  app/res/drawable-mdpi/ic_blue_forward.png
  app/res/drawable-mdpi/icon_chevron_left_brand.png
  app/res/drawable-mdpi/icon_chevron_right_brand.png
  app/res/drawable-xhdpi/ic_blue_backward.png
  app/res/drawable-xhdpi/ic_blue_forward.png
  app/res/drawable-xhdpi/icon_chevron_left_brand.png
  app/res/drawable-xhdpi/icon_chevron_right_brand.png
  app/res/drawable-xxhdpi/ic_blue_backward.png
  app/res/drawable-xxhdpi/ic_blue_forward.png
  app/res/drawable/icon_auto_advance_arrow.png
  app/res/drawable/icon_chevron_left_brand.png
  app/res/drawable/icon_chevron_left_primary.png
  app/res/drawable/icon_chevron_right_brand.png
  app/res/drawable/icon_chevron_right_primary.png
  app/res/drawable/icon_new.png
  app/res/drawable/icon_next.png
  app/res/layout/screen_form_entry.xml
  app/res/layout/square_button_text.xml
  app/res/layout/square_card.xml
  app/res/values-w320dp/dimens.xml
  app/res/values-w600dp/dimens.xml
  app/res/values-w720dp/dimens.xml
  app/res/values/dimens.xml
Labels: QA Note

#2967 Messaging icon improvements
  app/res/drawable/ic_connect_menu_notification.xml
  app/res/drawable/ic_connect_menu_notification_none.xml
  app/res/drawable/ic_connect_messaging_base.xml
  app/res/drawable/ic_connect_messaging_unread.xml
  app/res/menu/menu_connect.xml
  app/res/menu/menu_connect_messaging.xml
  app/src/org/commcare/activities/connect/ConnectActivity.java
Labels: cross requested, skip-integration-tests

#2966 Messaging push notification improvements
  app/res/drawable-night/ic_connect_message_large.xml
  app/res/drawable/ic_connect_menu_notification.xml
  app/res/drawable/ic_connect_menu_notification_none.xml
  app/res/drawable/ic_connect_message_large.xml
  app/res/drawable/ic_connect_messaging_base.xml
  app/res/drawable/ic_connect_messaging_unread.xml
  app/res/menu/menu_connect.xml
  app/res/menu/menu_connect_messaging.xml
  app/res/values-pt/strings.xml
  app/res/values-ti/strings.xml
  app/res/values/strings.xml
  app/src/org/commcare/CommCareNoficationManager.java
  app/src/org/commcare/activities/connect/ConnectActivity.java
  app/src/org/commcare/services/CommCareFirebaseMessagingService.java
Labels: cross requested, skip-integration-tests

#2971 Automatic encryption key retrieval for messaging channels
  app/src/org/commcare/connect/MessageManager.java
  app/src/org/commcare/connect/network/ApiConnectId.java
Labels: QA Note

#2986 Logging empty push notifications
  app/src/org/commcare/services/CommCareFirebaseMessagingService.java
Labels: cross requested, skip-integration-tests

#2983 Register broadcast receivers with proper security
  app/src/org/commcare/fragments/connectId/ConnectIdPhoneVerificationFragmnet.java
  app/src/org/commcare/fragments/connectId/ConnectIdUserDeactivateOTPVerificationFragment.java
Labels: cross requested, skip-integration-tests

#2984 Additional logging for failed HQ token auth in ConnectID-managed apps.
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/connect/ConnectManager.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
Labels: cross requested, skip-integration-tests

#2985 Fix sync buttons in learn and delivery progress pages
  app/src/org/commcare/activities/connect/ConnectActivity.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
  app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
Labels: cross requested, skip-integration-tests

#2989 Delivery Progress UI fix
  app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
Labels: cross requested, skip-integration-tests

#2997 Add HQ credentials to build configuration when running AGP connected tasks
  app/build.gradle
Labels: product/invisible
