Repository dimagi/commcare-android, pull requests merged in 2025-09, with the labels that each got.

#3320 Updated credential api to user userId
  app/src/org/commcare/activities/connect/viewmodel/PersonalIdCredentialViewModel.kt
  app/src/org/commcare/connect/network/ApiPersonalId.java
  app/src/org/commcare/connect/network/connectId/PersonalIdApiHandler.java
Labels: skip-integration-tests

#3312 Cosmetic changes for worker history
  app/res/layout/fragment_earned_credential.xml
  app/res/layout/fragment_pending_credential.xml
  app/res/menu/menu_work_history.xml
  app/res/values-es/strings.xml
  app/res/values-fr/strings.xml
  app/res/values-hi/strings.xml
  app/res/values-pt/strings.xml
  app/res/values-sw/strings.xml
  app/res/values-ti/strings.xml
  app/res/values/strings.xml
  app/src/org/commcare/fragments/personalId/EarnedCredentialFragment.kt
  app/src/org/commcare/fragments/personalId/PendingCredentialFragment.kt
Labels: skip-integration-tests

#3325 Shown opportunities from local DB in case internet connectivity issue
  app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
Labels: skip-integration-tests

#3326 Bump Min SDK to API 23
  app/build.gradle
  app/src/org/commcare/CommCareNoficationManager.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/android/security/RsaKeyStoreHandler.kt
  app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/utils/BiometricsHelper.java
  app/src/org/commcare/utils/EncryptionKeyProvider.java
  app/src/org/commcare/utils/NotificationUtil.java
  app/src/org/commcare/views/dialogs/PinnedNotificationWithProgress.java
  app/src/org/commcare/views/widgets/AudioRecordingService.java
  app/unit-tests/resources/robolectric.properties
  app/unit-tests/src/org/commcare/android/shadows/SQLiteCursorNative.java
  app/unit-tests/src/org/commcare/utils/EncryptionUtilsTest.java
  app/unit-tests/src/org/commcare/utils/MockAndroidKeyStoreProvider.java
  app/unit-tests/src/org/commcare/utils/MockEncryptionKeyProvider.java
  app/unit-tests/src/org/commcare/utils/MockKeyGenerator.java
  app/unit-tests/src/org/commcare/utils/MockKeyGeneratorSpi.java
  app/unit-tests/src/org/commcare/utils/MockKeyStore.java
  commcare-support-library/build.gradle
Labels: QA Note

#3351 Hide "this is not me" Button
  app/res/layout/fragment_recovery_code.xml
  app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
Labels: Release Note, skip-integration-tests
