Repository dimagi/commcare-android, pull requests merged in 2025-04, with the labels that each got.

#3006 Fixing obsolete app selector code
  app/src/org/commcare/activities/LoginActivity.java
Labels: cross requested, skip-integration-tests

#3005 CCCT-890
  app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
  app/src/org/commcare/android/database/connect/models/ConnectUserRecord.java
  app/src/org/commcare/connect/database/ConnectAppDatabaseUtil.java
  app/src/org/commcare/connect/database/ConnectJobUtils.java
  app/src/org/commcare/fragments/connectId/ConnectIDSignupFragment.java
Labels: cross requested, skip-integration-tests

#3007 Changes to delivery progress text for each payment unit
  app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java
Labels: cross requested, skip-integration-tests

#3009 Delivery progress scrolling fix
  app/res/layout/fragment_connect_delivery_progress.xml
Labels: cross requested, skip-integration-tests

#3010 Additional tweaks to delivery progress text
  app/res/layout/view_job_card.xml
  app/res/layout/view_progress_job_card.xml
  app/res/values-pt/strings.xml
  app/res/values-sw/strings.xml
  app/res/values-ti/strings.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/StandardHomeActivityUIController.java
  app/src/org/commcare/adapters/ConnectDeliveryProgressReportAdapter.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
  app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
Labels: cross requested, skip-integration-tests

#3011 Pm 7615
  app/res/navigation/nav_graph_connectid.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/connect/ConnectIdActivity.java
  app/src/org/commcare/fragments/connectId/ConnectIDSecondaryPhoneNumber.java
  app/src/org/commcare/fragments/connectId/ConnectIdPinFragment.java
Labels: cross requested, skip-integration-tests

#3012 PM QA 7620
  app/src/org/commcare/connect/database/ConnectUserDatabaseUtil.java
Labels: cross requested, skip-integration-tests

#3013 Additional delivery progress tweak
  app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
Labels: skip-integration-tests

#2996 Graceful error handling for SSO token retrieval
  app/assets/locales/android_translatable_strings.txt
  app/res/values/strings.xml
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/connect/ConnectManager.java
  app/src/org/commcare/connect/MessageManager.java
  app/src/org/commcare/connect/network/ApiConnect.java
  app/src/org/commcare/connect/network/ApiConnectId.java
  app/src/org/commcare/connect/network/ConnectNetworkHelper.java
  app/src/org/commcare/connect/network/ConnectSsoHelper.java
  app/src/org/commcare/connect/network/IApiCallback.java
  app/src/org/commcare/connect/network/TokenRequestDeniedException.kt
  app/src/org/commcare/connect/network/TokenUnavailableException.kt
  app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
  app/src/org/commcare/engine/references/JavaHttpReference.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
  app/src/org/commcare/fragments/connect/ConnectUnlockFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIDSecondaryPhoneNumber.java
  app/src/org/commcare/fragments/connectId/ConnectIDSignupFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdPhoneFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdPhoneVerificationFragmnet.java
  app/src/org/commcare/fragments/connectId/ConnectIdPinFragment.java
  app/src/org/commcare/fragments/connectId/ConnectIdUserDeactivateOTPVerificationFragment.java
  app/src/org/commcare/network/CommcareRequestGenerator.java
  app/src/org/commcare/network/HttpCalloutTask.java
  app/src/org/commcare/tasks/ManageKeyRecordTask.java
  app/src/org/commcare/views/notifications/NotificationMessageFactory.java
Labels: cross requested, skip-integration-tests

#3015 Potential Fix for CyclicPurgeTest
  app/src/org/commcare/views/dialogs/AlertDialogFragment.java
  app/unit-tests/src/org/commcare/android/tests/formsave/CyclicCasesPurgeTest.java
Labels: skip-integration-tests

#3014 Passthrough EXIF properties while scaling image
  app/build.gradle
  app/src/org/commcare/utils/FileUtil.java
Labels: skip-integration-tests, 🙋 Bounty claim

#2978 Set CC version in form metadata in SemVer format
  app/assets/locales/android_translatable_strings.txt
  app/src/org/commcare/AppUtils.java
Labels: Release Note

#2977 Add device model and android version to device logs
  app/src/org/commcare/android/logging/ForceCloseLogSerializer.java
  app/src/org/commcare/logging/DeviceReportWriter.java
Labels: product/invisible

#3020 Biometric config cleanup and error handling
  app/res/values-pt/strings.xml
  app/res/values-sw/strings.xml
  app/res/values-ti/strings.xml
  app/res/values/strings.xml
  app/src/org/commcare/activities/connect/ConnectIdActivity.java
  app/src/org/commcare/connect/ConnectManager.java
  app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
  app/src/org/commcare/utils/BiometricsHelper.java
Labels: cross requested, skip-integration-tests

#3024 Logs SSL exception when trying to download app
  app/src/org/commcare/engine/resource/ResourceInstallUtils.java
Labels: skip-integration-tests

#3027 Commcare 2.56
  app/AndroidManifest.xml
  app/build.gradle
  app/res/values/strings.xml
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/entity/AndroidAsyncNodeEntityFactory.kt
  app/src/org/commcare/logging/analytics/TimedStatsTracker.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/tasks/EntityCacheInvalidationWorker.kt
  app/src/org/commcare/tasks/EntityLoaderHelper.kt
  app/src/org/commcare/tasks/EntityLoaderTask.java
  app/src/org/commcare/tasks/ManageKeyRecordTask.java
  app/src/org/commcare/tasks/PrimeEntityCache.kt
  app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
  app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java
Labels: cross requested, skip-integration-tests

#3033 Fixed logic around receiving and storing Connect DB passphrases.
  app/src/org/commcare/connect/database/ConnectDatabaseHelper.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
Labels: cross requested, skip-integration-tests

#3022 Respect image orientation while previewing the image in mobile app
  app/src/org/commcare/utils/MediaUtil.java
  app/unit-tests/src/org/commcare/android/tests/ImageInflationTest.java
Labels: 🙋 Bounty claim

#3044 -update the missing code, and change the request code value
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/LoginActivityUIController.java
  app/src/org/commcare/connect/ConnectConstants.java
  app/src/org/commcare/connect/ConnectIDManager.java
  app/src/org/commcare/connect/database/ConnectAppDatabaseUtil.java
  app/src/org/commcare/connect/database/ConnectJobUtils.java
  app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
  app/src/org/commcare/fragments/SelectInstallModeFragment.java
  app/src/org/commcare/utils/CrashUtil.java
  app/src/org/commcare/utils/EncryptionKeyAndTransform.java
Labels: cross requested

#3047 Fixed signup blocker
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/connect/ConnectIDManager.java
  app/src/org/commcare/preferences/AppManagerDeveloperPreferences.java
Labels: cross requested, skip-integration-tests

#3042 Remove reliance on No UI Fragments with set retain instance to store state
  app/res/layout/choice_dialog_three_panel.xml
  app/src/org/commcare/activities/AppManagerActivity.java
  app/src/org/commcare/activities/CallOutActivity.java
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/CommCareFormDumpActivity.java
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/CommCareWiFiDirectActivity.java
  app/src/org/commcare/activities/CreatePinActivity.java
  app/src/org/commcare/activities/DrawActivity.java
  app/src/org/commcare/activities/DriftHelper.java
  app/src/org/commcare/activities/EntitySelectActivity.java
  app/src/org/commcare/activities/FormEntryActivity.java
  app/src/org/commcare/activities/FormEntryActivityUIController.java
  app/src/org/commcare/activities/FormRecordListActivity.java
  app/src/org/commcare/activities/GeoPointActivity.java
  app/src/org/commcare/activities/HomeScreenBaseActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/PromptApkUpdateActivity.java
  app/src/org/commcare/activities/RefreshToLatestBuildActivity.java
  app/src/org/commcare/activities/SingleAppManagerActivity.java
  app/src/org/commcare/activities/SyncCapableCommCareActivity.java
  app/src/org/commcare/activities/UnrecoverableErrorActivity.java
  app/src/org/commcare/activities/components/FormEntryDialogs.java
  app/src/org/commcare/fragments/BreadcrumbBarHelper.java
  app/src/org/commcare/fragments/ContainerFragment.java
  app/src/org/commcare/fragments/ContainerViewModel.java
  app/src/org/commcare/fragments/SelectInstallModeFragment.java
  app/src/org/commcare/fragments/TaskConnectorViewModel.java
  app/src/org/commcare/preferences/AdvancedActionsPreferences.java
  app/src/org/commcare/preferences/MainConfigurablePreferences.java
  app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresPresenter.java
  app/src/org/commcare/utils/AndroidShortcuts.java
  app/src/org/commcare/utils/ApkDependenciesUtils.kt
  app/src/org/commcare/utils/GeoUtils.java
  app/src/org/commcare/utils/Permissions.java
  app/src/org/commcare/utils/TemplatePrinterUtils.java
  app/src/org/commcare/views/UserfacingErrorHandling.java
  app/src/org/commcare/views/dialogs/AlertDialogFragment.java
  app/src/org/commcare/views/dialogs/CommCareAlertDialog.java
  app/src/org/commcare/views/dialogs/CustomViewAlertDialog.java
  app/src/org/commcare/views/dialogs/DialogCreationHelpers.java
  app/src/org/commcare/views/dialogs/HorizontalPaneledChoiceDialog.java
  app/src/org/commcare/views/dialogs/PaneledChoiceDialog.java
  app/src/org/commcare/views/dialogs/StandardAlertDialog.java
  app/src/org/commcare/views/widgets/ImageWidget.java
  app/unit-tests/src/org/commcare/utils/RobolectricUtil.java
  scripts/browserstack.py
Labels: QA Note
