Repository dimagi/commcare-android, pull requests merged in 2025-08, with the labels that each got.

#3250 Retrofit applied to connectId token and connect heart beat
  app/src/org/commcare/connect/network/ApiPersonalId.java
  app/src/org/commcare/connect/network/ApiService.java
  app/src/org/commcare/connect/network/ConnectSsoHelper.java
  app/src/org/commcare/connect/network/base/BaseApiCallback.kt
  app/src/org/commcare/connect/network/base/BaseApiHandler.kt
  app/src/org/commcare/connect/network/connectId/PersonalIdApiHandler.java
  app/src/org/commcare/connect/network/connectId/parser/ConnectTokenResponseParser.kt
  app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
Labels: skip-integration-tests

#3234 Phase-I for retrofit in connect call
  app/res/values-es/strings.xml
  app/res/values-fr/strings.xml
  app/res/values-hi/strings.xml
  app/res/values-lt/strings.xml
  app/res/values-no/strings.xml
  app/res/values-pt/strings.xml
  app/res/values-sw/strings.xml
  app/res/values-ti/strings.xml
  app/res/values/strings.xml
  app/src/org/commcare/android/integrity/IntegrityReporterWorker.kt
  app/src/org/commcare/connect/ConnectJobHelper.kt
  app/src/org/commcare/connect/network/ApiConnect.java
  app/src/org/commcare/connect/network/ApiEndPoints.java
  app/src/org/commcare/connect/network/ApiPersonalId.java
  app/src/org/commcare/connect/network/ApiService.java
  app/src/org/commcare/connect/network/ConnectNetworkHelper.java
  app/src/org/commcare/connect/network/ConnectSsoHelper.java
  app/src/org/commcare/connect/network/NoParsingResponseParser.kt
  app/src/org/commcare/connect/network/base/BaseApi.kt
  app/src/org/commcare/connect/network/base/BaseApiCallback.kt
  app/src/org/commcare/connect/network/base/BaseApiHandler.kt
  app/src/org/commcare/connect/network/base/BaseApiResponseParser.kt
  app/src/org/commcare/connect/network/connect/ConnectApiHandler.kt
  app/src/org/commcare/connect/network/connect/models/ConnectOpportunitiesResponseModel.kt
  app/src/org/commcare/connect/network/connect/models/DeliveryAppProgressResponseModel.kt
  app/src/org/commcare/connect/network/connect/models/LearningAppProgressResponseModel.kt
  app/src/org/commcare/connect/network/connect/parser/ConnectOpportunitiesParser.kt
  app/src/org/commcare/connect/network/connect/parser/DeliveryAppProgressResponseParser.kt
  app/src/org/commcare/connect/network/connect/parser/LearningAppProgressResponseParser.kt
  app/src/org/commcare/connect/network/connectId/PersonalIdApiErrorHandler.java
  app/src/org/commcare/connect/network/connectId/PersonalIdApiHandler.java
  app/src/org/commcare/connect/network/connectId/parser/ConnectTokenResponseParser.kt
  app/src/org/commcare/connect/network/connectId/parser/ReportIntegrityResponseParser.java
  app/src/org/commcare/connect/network/connectId/parser/RetrieveCredentialsResponseParser.kt
  app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
  app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
  app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
  app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
  app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
  app/src/org/commcare/fragments/connect/ConnectUnlockFragment.java
  app/src/org/commcare/services/PaymentAcknowledgeReceiver.java
Labels: skip-integration-tests

#3291 Android 15 compatibility changes
  app/build.gradle
  app/res/values/themes.xml
  commcare-support-library/build.gradle
Labels: Release Note, QA Note

#3288 Smallish changes From final Connect Review
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/activities/StandardHomeActivity.java
  app/src/org/commcare/activities/StandardHomeActivityUIController.java
  app/src/org/commcare/activities/connect/ConnectActivity.java
  app/src/org/commcare/android/logging/ReportingUtils.java
  app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
  app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
Labels: skip-integration-tests

#3081 SQLCipher migration (android-database-sqlcipher -> sqlcipher-android)
  app/build.gradle
  app/proguard.cfg
  app/src/org/commcare/AppUtils.java
  app/src/org/commcare/CommCareApp.java
  app/src/org/commcare/CommCareApplication.java
  app/src/org/commcare/adapters/EntityStringFilterer.java
  app/src/org/commcare/android/database/user/models/FormRecord.java
  app/src/org/commcare/connect/database/ConnectDatabaseHelper.java
  app/src/org/commcare/engine/cases/CaseUtils.java
  app/src/org/commcare/models/database/AndroidDbHelper.java
  app/src/org/commcare/models/database/AndroidSandbox.java
  app/src/org/commcare/models/database/ConcreteAndroidDbHelper.java
  app/src/org/commcare/models/database/DbUtil.java
  app/src/org/commcare/models/database/EncryptedDatabaseAdapter.java
  app/src/org/commcare/models/database/HybridFileBackedSqlHelpers.java
  app/src/org/commcare/models/database/HybridFileBackedSqlStorage.java
  app/src/org/commcare/models/database/IDatabase.java
  app/src/org/commcare/models/database/IndexedFixturePathUtils.java
  app/src/org/commcare/models/database/SqlStorage.java
  app/src/org/commcare/models/database/app/AppDatabaseSchemaManager.java
  app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
  app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
  app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
  app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
  app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
  app/src/org/commcare/models/database/global/GlobalDatabaseSchemaManager.java
  app/src/org/commcare/models/database/global/GlobalDatabaseUpgrader.java
  app/src/org/commcare/models/database/migration/FixtureSerializationMigration.java
  app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
  app/src/org/commcare/models/database/user/DemoUserBuilder.java
  app/src/org/commcare/models/database/user/UserDatabaseSchemaManager.java
  app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
  app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
  app/src/org/commcare/models/database/user/UserSandboxUtils.java
  app/src/org/commcare/models/database/user/models/AndroidCaseIndexTable.java
  app/src/org/commcare/models/database/user/models/AndroidCaseIndexTablePreV21.java
  app/src/org/commcare/models/database/user/models/CommCareEntityStorageCache.java
  app/src/org/commcare/services/CommCareSessionService.java
  app/src/org/commcare/sync/FormSubmissionHelper.java
  app/src/org/commcare/sync/ProcessAndSendTask.java
  app/src/org/commcare/tasks/DataPullTask.java
  app/src/org/commcare/utils/AppLifecycleUtils.java
  app/src/org/commcare/xml/AndroidBulkCaseXmlParser.java
  app/src/org/commcare/xml/AndroidCaseXmlParser.java
  app/unit-tests/src/org/commcare/CommCareTestApplication.java
  app/unit-tests/src/org/commcare/android/shadows/SQLiteCursorNative.java
  app/unit-tests/src/org/commcare/android/shadows/SQLiteDatabaseNative.java
  app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java
  app/unit-tests/src/org/commcare/android/util/TestUtils.java
  app/unit-tests/src/org/commcare/models/database/UnencryptedDatabaseAdapter.java
  app/unit-tests/src/org/commcare/models/database/app/DatabaseAppOpenHelperMock.java
  app/unit-tests/src/org/commcare/models/database/global/DatabaseGlobalOpenHelperMock.java
  app/unit-tests/src/org/commcare/models/database/user/DatabaseUserOpenHelperMock.java
Labels: product/invisible, QA Note

#3299 Side nav drawer in App Home page
  app/res/layout/nav_drawer_sublist_item.xml
  app/src/org/commcare/activities/CommCareActivity.java
  app/src/org/commcare/activities/CommCareSetupActivity.java
  app/src/org/commcare/activities/DispatchActivity.java
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/activities/StandardHomeActivity.java
  app/src/org/commcare/connect/ConnectConstants.java
  app/src/org/commcare/navdrawer/BaseDrawerActivity.kt
  app/src/org/commcare/navdrawer/BaseDrawerController.kt
  app/src/org/commcare/navdrawer/NavDrawerAdapter.kt
  app/src/org/commcare/navdrawer/NavDrawerParentItem.kt
Labels: QA Note

#3300 Keep showing sidenav drawer on Login once shown
  app/src/org/commcare/activities/LoginActivity.java
  app/src/org/commcare/navdrawer/NavDrawerHelper.kt
Labels: QA Note
